### ISSUE TITLE
fix: Show latest deployed version

### ISSUE THREAD

**Issue by tremblaymath** [ovh/cds#1057]
I rolled back from version 32 to 25 but it still display 32 and history is not ordered by Start date

![capture d ecran 2017-09-11 a 13 37 12](https://user-images.githubusercontent.com/10472038/30288331-5b658ea8-96f6-11e7-8ba8-81cc9212431a.png)
![capture d ecran 2017-09-11 a 13 36 47](https://user-images.githubusercontent.com/10472038/30288330-5b5ef0b6-96f6-11e7-9f9d-d93beace5018.png)

**Comment by yesnault** [comment]
The workflow tab show the latest version, so 32 per default. You can switch the version on workflow tab to see another version.
We prepare a lot of features with the new Workflow feature, you will see easily the latest run of your workflow. If you re-run the version 25 -> it should be 25 in your environment too after deploy.

On history tab, it's sorted by version too -> issue for that: https://github.com/ovh/cds/issues/1058
