### ISSUE TITLE
GitClone

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#1079]
and step script after -> git tag returns no tags.

**Comment by yesnault** [comment]
git ls-remote --tags origin is ok

**Comment by klamrosek** [comment]
I have also other problem after using GitClone step. Command 'git diff' returns error:
`+ git diff origin/prod..origin/preprod
fatal: ambiguous argument 'origin/prod..origin/preprod': unknown revision or path not in the working tree.`
If I will use CDS_GitClone instead of GitClone it works fine.

**Comment by yesnault** [comment]
so, the behaviour for now:
if there is a commit hash, there is git clone, then git rebase on commit.
if there is no commit hash, there is git clone with depth=0 -> git tag/ diff / modules don't work.
We  probably add an option to set or not depth.

**Comment by yesnault** [comment]
Ok, fix. We remove depth for now.
