### ISSUE TITLE
plugin-kafka-publish: CDS server doesn't correctly handle ACK.

### ISSUE THREAD

**Issue by byo** [ovh/cds#1108]
There are some issues processing ACK sent from the worker when using kafka plugin.
In some cases, the server receives ACK message but then waits up to 10 minutes to finalize the task.
In some cases, the server doesn't receive ACK and standard task timeout happens.

This behavior seems non-deterministic. Sometimes there's no issue for few runs, sometimes it happens in 50% runs.

When the server is waiting to finalize the task, here's the log on CDS ui:

> Starting step /plugin-kafka-publish-1
> Data sent to cds-runner.main : [message]
> Waiting ACK on *** on topic cds-runner.main...
> Got ACK from cds-runner.main : OK

Once it finalizes the task, the log is:
> Starting step /plugin-kafka-publish-1
> Data sent to cds-runner.main : [message]
> Waiting ACK on *** on topic cds-runner.main...
> Got ACK from cds-runner.main : OK
> 
> End of step /plugin-kafka-publish-1 [Success]

**Comment by fsamin** [comment]
From your logs, i can read that you use the same kafka topic for sending data and receiving ack. Can you confirm ?  If so, you should try with different topics, as told in the documentation.
