### ISSUE TITLE
send on closed channel

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#1153]
cds-api_1             | panic: send on closed channel
cds-api_1             |
cds-api_1             | goroutine 69 [running]:
cds-api_1             | github.com/ovh/cds/engine/api.(*lastUpdateBroker).Start(0xc42034eaa0, 0x27192c0, 0xc42005a100, 0xc4201fd2a0, 0x27201e0, 0xc4201fd260)
cds-api_1             | 	/go/src/github.com/ovh/cds/engine/api/lastupdate.go:130 +0x54c
cds-api_1             | created by github.com/ovh/cds/engine/api.(*lastUpdateBroker).Init
cds-api_1             | 	/go/src/github.com/ovh/cds/engine/api/lastupdate.go:38 +0xc3

**Comment by fsamin** [comment]
Avoid closing the channel and let the GC do free all the thing is fine but, it seems that `lastUpdateBroker.clients` leaks. The case `<-w.(http.CloseNotifier).CloseNotify()`never occurs and the goroutine which listen to the channel never exits

https://github.com/ovh/cds/compare/fix1153?expand=1

**Comment by fsamin** [comment]
cf #1171
