### ISSUE TITLE
fix (ui): Relaunch / Stop / Run with Parameters btn not disabled if the user does not have execute rights

### ISSUE THREAD

**Issue by neyaled** [ovh/cds#1278]
This is maybe more a feature than an issue as the rights are correctly handled
but this happens for the following conditions:

A user has read-execute rights on an application and read rights on a pipeline.
For this given pipeline, the "launch" icon will be displayed and the user is able
to click on it which then leads to a popup indicating that the action is indeed forbidden.

The best behavior would be to hide the launch icon therefore removing any possible confusion.

**Comment by fsamin** [comment]
@bnjjj is it fixed on workflows ?
if so, let's close it

**Comment by bnjjj** [comment]
I think yes it’s fixed

**Comment by yesnault** [comment]
It's ok for Run Workflow.

It's not ok for Stop / Relaunch / Run Pipeline with parameters. 

Example: here: https://github.com/ovh/cds/blob/d43f966ab4e508e231ca1933f52f382633b23fd1/ui/src/app/views/workflow/run/summary/workflow.run.summary.html#L68, the value of workflowRun.workflow.permission (stored in DB) does not contains de permission for the current user.

cc @bnjjj @fsamin

**Comment by sguiheux** [comment]
Run + Relaunch already fixed.
Stop will be fix by #3007

**Comment by yesnault** [comment]
f
