### ISSUE TITLE
fix (api): serve 32 bits worker binary

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#1287]
* Update the make file to build the 32 bits worker binary
* Serve a new route `/download/worker/x86` for 32 bits binary and keep `/download/worker/x86_64` for 64 bits binary.

**Comment by yesnault** [comment]
remove route /download/worker and use only new routes
Impacts : users & hatcheries

**Comment by yesnault** [comment]
hum.. on *nix system, it's really useful to do:

```wget -nv https://your-cds-api/download/worker/`uname -m` -O worker```

Our hatcheries spawn worker with 
```curl %s/download/worker/`uname -m```

So, it's the easiest way to take the good worker.

Proposition:
Route /download/worker/x86_64 can be an alias on /download/cds-worker-linux-amd64
And a new routes, alias on /download/cds-worker-linux-i386
/download/worker/i386
/download/worker/i686
