### ISSUE TITLE
Research bar not working

### ISSUE THREAD

**Issue by FredericEspiau** [ovh/cds#1306]
Hey,

when typing text in the search bar in the top left part of the screen, the search works well but I can't click on results. Keyboard navigation works though (down key until I get to the result I want to open and then enter).

Browser: Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Thanks

**Comment by bnjjj** [comment]
Thanks ! In fact when it's in the last element of the dropdown there is a bug, no effect on click. We'll check

**Comment by FredericEspiau** [comment]
It's doesn't seem to happen only with the last item of the list. Sometimes, with the same research on the same screen, the last working item position changes

**Comment by sguiheux** [comment]
https://github.com/edcarroll/ng2-semantic-ui/issues/316

**Comment by FredericEspiau** [comment]
It works now, I close :)
