### ISSUE TITLE
New permission per group or per user

### ISSUE THREAD

**Issue by ncrocfer** [ovh/cds#1594]
I have to add a new user with Read permission in one of my applications but I can not, I must create a new group with the wanted permission, and next add the user in this group.

It would be great if we could add a new permission in an application directly linked to a user and not to a group :)

**Comment by yesnault** [comment]
Hi. Yes, all permissions are managed by group and not by user. Permission management is complex (on project, application, environment, pipeline and then workflow): add permission management by user is something that will add more complexity.
Perhaps we could add something to easily create group with a user, directly on UI: go on permission section of one application -> add a new group (and select users to add on it), select right on application and save.
