### ISSUE TITLE
feat (ui): add admin view in CDS for administrator

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#1625]

**Comment by yesnault** [comment]
Admin status -> https://github.com/ovh/cds/pull/1740
TODO -> 
- workers and action to change disable a worker
- worker model with direct link to worker model settings
- Queue : Workflow Run Job Waiting, and action to stop one or many workflow
- Current Workflow Run Job Building
- Overwall Status page: NB Queue, Nb Building, Resume Status (red if 1 AL on status page)
