### ISSUE TITLE
Cannot open test_results.xml artifact in chromium/firefox

### ISSUE THREAD

**Issue by neyaled** [ovh/cds#1706]
The following error is shown when trying to open a test_results.xml:

This page contains the following errors:  error on line 1 at column 39: Document is empty Below is a rendering of the page up to the first error.

Using links/lynx it works.

Example of a line 1 causing the issue:
"""
\<xml version="1.0" encoding="utf-8"?\>\n\<testsuites\>                                                                                                                                          
"""

**Comment by yesnault** [comment]
It's a venom issue here: https://github.com/ovh/venom/blob/master/venom_output.go#L41
