### ISSUE TITLE
Ergo: date display

### ISSUE THREAD

**Issue by landru29** [ovh/cds#2101]
In the workflow execution panel (main panel + left-side panel), the dates are displayed like:
` 1/30/18, 10:27 AM`

It would be better to display:
`01/30/18, 10:27 (few minutes ago)`, using [momentjs - fromNow()](https://momentjs.com/docs/#/displaying/fromnow/) for human dates

**Comment by richardlt** [comment]
In history of pipeline runs, given date is not valid for running pipeline.

**Comment by richardlt** [comment]
Looks like there is an issue to display date for fr locale, maybe if language is missing in browser.
