### ISSUE TITLE
fix(worker): missing flags in CLI Usage

### ISSUE THREAD

**Issue by timlegrand** [ovh/cds#2120]
Hello,

The `worker update` command shows this as Usage:
```Usage:
  worker update [flags]

Flags:
      --from-github   Update binary from latest github release
  -h, --help          help for update

Global Flags:
[...]
```
This way, it looks like flags are optional. But it seems that `--api` and `--token` global flags are mandatory.

**Comment by sguiheux** [comment]
CLI  up to date
Doc up to date
