### ISSUE TITLE
feat(api): support ssh objectstore

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#2177]

**Comment by fsamin** [comment]
support for FUSE instead (https://github.com/hanwen/go-fuse) could be an option to support sshfs, webdav, s3, ...

https://github.com/libfuse/libfuse/wiki/Filesystems

**Comment by yesnault** [comment]
objectstore covered by cdn now (Local, Swift, S3, Webdav supported) - doc https://ovh.github.io/cds/docs/components/cdn/
