### ISSUE TITLE
feat(action): improve move

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#2185]
Hello,

Is it possible to improve the "move" of an action? Like add shortcuts to  "move to the top/bottom":
https://plik.root.gg/file/k2QHmxu67Dxz1LIP/RKXrKrlUXiO4BjwG/CDS_move.png

It's just a proposal ;-).

**Comment by bnjjj** [comment]
Do you have try to collapse all the actions and move them with drag and drop ?

**Comment by blaryjp** [comment]
I don't see a "collapse all" button

**Comment by bnjjj** [comment]
you will see that :D
