### ISSUE TITLE
fix(api): add triggered_by for scheduler

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#2189]

**Comment by yesnault** [comment]
@bnjjj I check, it's in https://github.com/ovh/cds/blob/master/engine/hooks/tasks.go#L324

**Comment by yesnault** [comment]
it's already here.

![image](https://user-images.githubusercontent.com/395454/36030236-affd5f14-0da6-11e8-9327-3771fd595a54.png)
![image](https://user-images.githubusercontent.com/395454/36030249-b7a3fe08-0da6-11e8-87f0-f88c36950070.png)
