### ISSUE TITLE
feat(wf): exit wf creation on click empty zone

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#2211]
Hello,

Is it possible to exit the workflow edition by clicking on an empty grey zone?
For now, the only way to exit is to click on the cross (see red rectangle).

https://plik.root.gg/file/EG9LxHQO4WQR0n6v/SQ5ffvpF37gWMeYy/CDS_clickoutside.png

Thx

**Comment by yesnault** [comment]
it's done. Select a node -> a modal is opened -> click en grey zone -> model is closed.
