### ISSUE TITLE
fix (ui): empty line

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#2216]
![capture d ecran 2018-02-13 a 12 55 21](https://user-images.githubusercontent.com/395454/36148685-2dab5e0c-10bd-11e8-8347-f274793c3edc.png)

will display

![capture d ecran 2018-02-13 a 12 53 24](https://user-images.githubusercontent.com/395454/36148677-20fbc4bc-10bd-11e8-8a23-72ad6706a3ee.png)

cc @henyxia

**Comment by bnjjj** [comment]
fixed
