### ISSUE TITLE
feat(cdsctl) Add a command to show status of running worflows

### ISSUE THREAD

**Issue by arnaudmorin** [ovh/cds#2226]
in previous cli (cds), I was using a command (ui?) which was showing me the status of currents builds ongoing in my project.
It could be nice if cdsctl let me do that also.

**Comment by yesnault** [comment]
it's `cdsctl ui` too -> show you current waiting & building workflows
`cdsctl shell` -> allows you to browse everything (project, workflows)... 

If you think of something else, feel free to re-open this issue
