### ISSUE TITLE
feat(ui): clone a pipeline

### ISSUE THREAD

**Issue by erdnaxeli** [ovh/cds#2265]
A button to clone a pipeline would be a nice feature.

Usage example: a noticed an error in my pipeline, I want to debug it, but I don't want to break other workflows using it. If I could clone it, it could then work on it and use it on my failing workflow.

**Comment by fsamin** [comment]
Pipeline reusability is a major feature in CDS. So cannot implement such a feature which is an anti-pattern in CDS (even if your use-case is a slightly different).

But we will implement a pipeline as code editor (such as workflow), so it will be really easy to copy and paste a pipeline

Would it be fine for you ?

**Comment by erdnaxeli** [comment]
Perfect.

Le 28 févr. 2018 08:12, "François Samin" <notifications@github.com> a
écrit :

**Comment by yesnault** [comment]
pipeline as code implemeted.
