### ISSUE TITLE
Parsing go2xunit file with Junit fails

### ISSUE THREAD

**Issue by maximecaruchet** [ovh/cds#2317]
It seems that a valid JUnit XML file is not parsed correctly in CDS: CDS shows that 0 tests are done when using the attached file with the JUnit plugin, however the file seems to be correctly formatted

[tests_results.txt](https://github.com/ovh/cds/files/1766240/tests_results.txt)

**Comment by fsamin** [comment]
Sorry the xml is not valid; we cant parse it properly
The CDATA is malformed; i think it's a bug on go2xunit; you should raise an issue on it
