### ISSUE TITLE
fix(ui): error when accessing to unexistent workflow

### ISSUE THREAD

**Issue by erdnaxeli** [ovh/cds#2322]
How to reproduce:

1. Go to a non existent workflow: ui/project/MYPROJECT/workflow/I-dont-exist
2. You get redirected to the workflows registry
3. Click on a workflow

What happens: blank page, and a javascript error 
![javascript error](https://user-images.githubusercontent.com/479441/36783106-57685adc-1c7b-11e8-81e0-d97d43947eb1.png)

What was expecetd: going to the workflow page

**Comment by sguiheux** [comment]
Same problem on application and pipeline
