### ISSUE TITLE
feat(api,ui,cli): banner

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#2331]
As a CDS Admin, I can (from the CLI or the UI) set a banner message (Maintenance scheduler on xx/xx/xx) with a level (info or warning).

As a CDS user using the web ui. If set, the banner should be displayed at the top of the page.
As a CDS user using the cli. If set the banner should be displayed on every command.

On API, the banner should be send as a header on every http response. Manage by the router and got from the cache.

**Comment by yesnault** [comment]
+ simple crud admin for add a news. News could be info/warning, and banner or not, or other com' solution

**Comment by yesnault** [comment]
broadcasts here. it remains the banner to do

**Comment by fsamin** [comment]
broadcasts are enough for the moment
