### ISSUE TITLE
fix(workflow): default rights creation

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#2337]
Hello,
When we create one new worflow, it doesn't set the same permissions than the project.
It's ok when we create one application, one pipeline, ... but not for wf. It's annoying.

**Comment by fsamin** [comment]
Hello, do you have an example ?

Here are the implemented rules:
* Every group with read permission on project can read the workflow
* On a workflow creation, only groups with RWX on the project have RWX permission on the workflow

**Comment by blaryjp** [comment]
Your second point is the problem.
Why don't you set the groups that have minimum READ on the wf?

**Comment by fsamin** [comment]
ok, got it; missing default RX project groups
