### ISSUE TITLE
Requirement type "plugin" not available at requirement creation.

### ISSUE THREAD

**Issue by ldec** [ovh/cds#2344]
When adding a new requirement, the type plugin is not available.
![cds_add_requirement](https://user-images.githubusercontent.com/6231281/36855289-5c10a06e-1d73-11e8-9b39-24ae8016505c.png)

However, it's available when editing an already existing requirement.
![cds_modify_requirement](https://user-images.githubusercontent.com/6231281/36855335-71c27932-1d73-11e8-8ffd-946f1b71d3a6.png)

**Comment by bnjjj** [comment]
It's a normal behavior. Because you don't need to manually add plugin requirement. When you add a step with usage of plugin the api will automatically add your plugin requirements. BTW I'm going to improve the update of your job to immediatly reflect the add of the plugin requirement in the UI
