### ISSUE TITLE
Cannot push Workflow if .cds have resources or directories

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2390]
Hello,

I pulled and updated a workflow into my git repository. This workflow relies on cds-specific configuration file that I would like to version in `.cds/` to avoid to clutter the repository.

When i run:

```bash
cdsctl workflow push APPCATALOG .cds/*
```

I get the error:

```
Reading file  .cds/AppCatalogWorkflow-v1.yml
Reading file  .cds/ApplicationCatalog.app.yml
Reading file  .cds/Playground.EU.env.yml
Reading file  .cds/build-v1-pip.yml
Reading file  .cds/deploy.pip.yml
Reading file  .cds/vault-file.json
Error: Invalid workflow (caused by: Unable to unmarshal workflow vault-file.json: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into exportentities.Workflow)
```

Then i tried to move the resource file in a subdirectory but without success:

```
Reading file  .cds/AppCatalogWorkflow-v1.yml
Reading file  .cds/ApplicationCatalog.app.yml
Reading file  .cds/Playground.EU.env.yml
Reading file  .cds/build-v1-pip.yml
Reading file  .cds/deploy.pip.yml
Reading file  .cds/resources
Error: read .cds/resources: is a directory
```

Is this use case supported ?

Regards,

**Comment by sguiheux** [comment]
Why not use cdsctl workflow push APPCATALOG .cds/*.yml  ?

**Comment by FabienM** [comment]
@sguiheux indeed it should do the trick, don't know why i did not found out this by myself, apart of a dumb reuse of a previous command.

BTW, i am still confused by the semantic differences of `workflow pull <object_name>` and `workflow push <filelist>`, since it seems a `workflow push <object_name>` could lead to a resolvable set of files without trying to import extra resources.

It's also unclear if future "as code" will import a "*.yml" glob or try to import all files. 

I close this one, anyway.
