### ISSUE TITLE
worker cache push /var/lib/docker

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#2451]
Error: worker cache push > Cannot tar : iterDirectory> cannot tar write (/var/lib/docker/overlay2/12551ac2c6b33aee15d54cc89892717c4084208afba88ba9e24e2050189a8a49/diff/lib/x86_64-linux-gnu/libBrokenLocale.so.1): tarWrite> cannot get resolve link: lstat libBrokenLocale-2.19.so: no such file or directory
--

**Comment by fsamin** [comment]
try with system' `tar` command

**Comment by yesnault** [comment]
won't fix, will be cover with persistent workspace (or custom worker model) with #4657
