### ISSUE TITLE
fix(api): import pipeline with forceUpdate does not guarantee new order or stages

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#2661]
I'm not very sure about that, but need test. I think when we import a pipeline which already exists and you want to move order of stages. It's not right

**Comment by fsamin** [comment]
We need a unit test to check this,  but it seems we don't update the stage attributes (like the order) on https://github.com/ovh/cds/blob/master/engine/api/pipeline/pipeline_importer.go#L128
