### ISSUE TITLE
md5 files in release

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#2702]
cc @nledez

**Comment by nledez** [comment]
May be better if it's a sha*
I use `sha512sum cds* sql.tar.gz ui.tar.gz > hashs-0.31.3` to generate one.

**Comment by yesnault** [comment]
done, deploy, see.  https://github.com/ovh/cds/releases/download/0.32.0/FILES

And sha512 is now displayed on UI CDS too (on each artifact uploaded)
