### ISSUE TITLE
Several errors about platforms

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2703]
####  when removing a platform linked to an application

```
curl 'https://interne.ovh.net/cds/ui/cdsapi/project/PROJECT_KEY/platforms/platform_name' -X DELETE -H 'Accept: application/json, text/plain, */*' -H 'Session-Token: xxx' --compressed
```
```json
{"message":"internal server error"}
```

#### can't remove a platform from the pipeline context

The UI seems to force a selected value

#### when a platform has been unlinked, pipeline contexts seems empty

But it is still impossible to remove the platform (500)

**Comment by sguiheux** [comment]
Because your platform is used by a workflow. But error message has to be improved

**Comment by bnjjj** [comment]
log that will help to debug
`-18 16:00:32 | warn | POST    | 500  | /project/XXX/application/XXXAPP/deployment/config/xxx 	 postApplicationDeploymentStrategyConfigHandler: SetDeploymentStrategy> unable to update deployment strategy: pq: more than one row returned by a subquery used as an expression`
