### ISSUE TITLE
Unwanted group

### ISSUE THREAD

**Issue by hmatias** [ovh/cds#2720]
When I use the CLI or the API a group is automatically created:

Groups already present:
    ./cds-release/cdsctl-linux-386 group list
    +----------------------------+
    |            NAME              |
    +----------------------------+
    | group1                        |
    | group2                        |
    | group3                        |
    | group4                        |
    +----------------------------+
     
I use the CLI to create a new project (same problem with the API):
(doc: cdsctl project create [ PROJECT-KEY PROJECT-NAME ] [GROUP-NAME])
./cds-release/cdsctl-linux-386 project create TEST test1 group1
     
    An unwanted group 'test1' is created by CDS:
    ./cds-release/cdsctl-linux-386 group list
    +----------------------------+
    |            NAME              |
    +----------------------------+
    | group1                        |
    | group2                        |
    | group3                        |
    | group4                        |
    | test1                            |
    +----------------------------+
     
    ./cds-release/cds-linux-amd64 -f creds.json project info TEST
    Project Key: BBTEST
    Project Name: test1
    Groups:
     - group1 7
     - test1 7

**Comment by bnjjj** [comment]
@hmatias Can you tell me if the PR #2763 fix this issue on your side ? If it's ok you can close this issue

**Comment by hmatias** [comment]
It's good for me.
Thanks
