### ISSUE TITLE
When removing a workflow, the starred link remains and can't be removed

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2806]
Hi,

Steps to reproduce:

1. create a WF
1. star it
1. remove the WF
1. Go to dashboard, the link is still there
1. trying to remove the star leads to a `404` error

**Comment by bnjjj** [comment]
It's an UI bug, in fact your bookmark doesn't exist anymore but you see the cache of the UI. With the PR #2687 it will solve the issue by sending an event to refresh list of bookmarks. cc @sguiheux
