### ISSUE TITLE
helm template implementation for kubernetes

### ISSUE THREAD

**Issue by jseguillon** [ovh/cds#2819]
Hi, helm is the package manager for kubernetes (https://helm.sh/). 
Would be great if cds could be installed with this tool, no ?

**Comment by bnjjj** [comment]
Yes you're right ! Waiting our PR on this subject maybe you could try https://github.com/kubernetes/kompose ? (Not tested personally)

**Comment by jseguillon** [comment]
Hell no. Easiest way is to start from another helm template.

I think I can do this but I have a question : reagrding cds-hatchery-swarm. It's requiring access to docker host engine. This is not recommended in Kubernetes. 

Can you detail what this connection is meant for ? Building docker images ? Starting new containers ? Both or maybe other stuffs ?

**Comment by yesnault** [comment]
@jseguillon hatchery swarm is not a requirement, you can use hatchery k8s instead :)

Hatchery (swarm, marathon, local, k8s, vsphere, openstack) spawned CDS Workers:
 - swarm / marathon / K8s : start container, each container download the worker from CDS API and run it
 - openstack / vsphere: create VMs, as container, each VMs download the worker from CDS API and run it -> theses CDS Workers are ofter used run 'docker build / push', this will avoid to do docker in docker.

**Comment by jseguillon** [comment]
Ok I see. I achieved creation of firsts pods, but i still have some questions : 
 - in your docker-compose, you start a container which launch the migrate command. Can you confirm this container can be stopped once  migration is done ? Also can you tell me what is the /sql parameter (a backup directory maybe) ? 
- do you have an example of a scaled CDS with two API server deployed ? is it supporte ? (when dealing with Kubernetes, you should always care about the way you can scale) ? 
- in a Kubernetes, buildig docker inside Kube is not re-commendend. Therefore is is usual to use a third party build service (for example Cloud Builder from Google). Do you think a plugin for these kind of service can be written as an Hatcherry ?  as a worker ?

**Comment by yesnault** [comment]
- the "--migrate-dir" is the directory which contains the sql files, you can view them on https://github.com/ovh/cds/tree/master/engine/sql
 - CDS API is full stateless. No master, no slave. You can start as many api as you want. There is two components to synchronize the flow: the redis (mandatory) and the database (postgresql). All data are stored in database, you have just to backup it. If you lost data on redis, it's not a problem.
 - yes, for using "docker binary", docker In Docker is not recommanded. We (on our production) use the hatcheries openstack / vshpere to spawn VM with docker inside.

**Comment by bnjjj** [comment]
It seems good :) if you have any questions, in order to have faster answer you can contact us via Gitter https://gitter.im/ovh-cds/Lobby

**Comment by yesnault** [comment]
yes, seems good. About the name on deployement / Pod, "cds" should be "cds-api" and "cds-gui" -> "cds-ui" to be consistent with the name inside the docke-compose https://github.com/ovh/cds/blob/master/docker-compose.yml#L53.

Then, cds-vcs, cds-hooks, cds-repositories for next services
