### ISSUE TITLE
Add a log action to plugin-kafka-publish

### ISSUE THREAD

**Issue by fpguy** [ovh/cds#2830]
Goal: add logs visible on the CDS side during the waiting time (execution of something long over kafka) 
The way it could be nice to be used:
plugin-kafka-publish log <usual login args> logs.txt

logs.txt to be received by the plugin on CDS side and not to be considered as an ACK, only appending the steps logs (where [XXX seconds] Please wait... is usually written)

At the end of the plugin-kafka step on CDS (ie proper ACK received), it could be a really nice to get all the successive logs as a single txt file (to be appended to artifact logging archive in my case)

Note: with such a feature it would be nice to increase the delay between 2 "[XXX seconds] Please wait..." to avoid flooding the logs

Thanks in advance =)

**Comment by yesnault** [comment]
seen both, no need anymore - won't fix.
