### ISSUE TITLE
Bug: pushing application "as code" invalidates platform tokens

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2867]
After a `cdsctl workflow push` containing an application, it is impossible to deploy this application on a platform, with the error:

```
1 | Starting step /DeployApplication-1
-- | --
2 | # Plugin OVH Arsenal Deployment Plugin vsnapshot is ready
3 | Deploying LhasaPreview on Arsenal at http://arsenal....
4 | # Details: deployment failure
5 | # Status: Fail
6 | Body:  {"error":"bad token: encoding/hex: invalid byte: U+002A '*'"}
```

Resetting the platform token fix the issue

**Comment by fsamin** [comment]
Did you check with the Arsenal team ?
This message is coming from Arsenal (of course the token may be corrupted in cds, but i can't reproduce the bug.
