### ISSUE TITLE
An edit on a ssh key in the "variables" section does not  affect the key in the "keys" section

### ISSUE THREAD

**Issue by HugoDelval** [ovh/cds#2940]
Step to reproduce:
* generate a ssh key in the "variables" section
* see that this key is added to the "keys" section
* edit the key in "variables" section (example: change the `login` part of the key)
* see that the key in the "keys" section has not been updated

**Comment by sguiheux** [comment]
@bnjjj with #2974 have to planned to do something for that?

**Comment by bnjjj** [comment]
not yet
