### ISSUE TITLE
Updating pipeline name does not affect variables that depends on it.

### ISSUE THREAD

**Issue by wI2L** [ovh/cds#2961]
Hello

I was using a pipeline called `make-build` that I renamed to build.
I was using the variable `{{.workflow.make-package.build.version}}` as version for a deployment platform. When I updated the pipeline name, the variable stayed the same and broke deployment.

Could it be possible to rename the variables of a project that reference a pipeline by this name ?

**Comment by bnjjj** [comment]
Do you relaunch a pipeline inside a workflow which is already run before renamed or no ?
Or is it a totally new workflow run (with a new major number)

**Comment by yesnault** [comment]
could be a warning on workflow

**Comment by yesnault** [comment]
yes, on roadmap warning
