### ISSUE TITLE
Dockerfiles

### ISSUE THREAD

**Issue by karantin2020** [ovh/cds#3063]
Hello. I created repo fo Dockerfiles https://github.com/karantin2020/cds-docker
It containes cds-engine and cds-ui Dockerfiles.

My hubs:
https://hub.docker.com/r/node3030/cds-engine
https://hub.docker.com/r/node3030/cds-ui

Images sizes are 4-5 times lower than yours.

Do you need this fixes?

**Comment by sguiheux** [comment]
Hi,
Our docker images contains all binaries for all distributions (cli, worker, hatcheries), and all architectures.
CDS Engine serve all binaries from routes : /download/{name}/{os}/{arch}

Moreover, CDS image uses binaries from github release and not master :)
