### ISSUE TITLE
fix(hook): rabbitmq doesn't work anymore in specific cases

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#3119]
steps to reproduce: `J'ai eu un soucis ce matin. J'ai stoppé l'ensemble de mes services CDS pour activer gops. Je relance. Le hook rabbitmq ne fonctionnait plus. J'ai fais retour arrière sur la conf, nada, et je n'avais aucun message d'err. J ai donc viré le hook et je l'ai recrée. Il n'est pas apparu dans la conf. J'ai tenté une seconde fois de recréer le hook, et là c'est tombé en marche`

**Comment by yesnault** [comment]
seems fixed
