### ISSUE TITLE
ASCII colors in job output are not displayed

### ISSUE THREAD

**Issue by wilfriedroset** [ovh/cds#3166]
Looks like CDS doesn't display colored text when displaying jobs output.
My job looks like this

```
NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
echo -e "${GREEN}OK${NC}"
```

The output display correctly OK but the green color aren't displayed.

**Comment by maxatome** [comment]
Output is HTML at the time of writing. So you can write HTML `font` tags as a workaround, or pipe your output to a script that does that for you.

What would be useful, is to have the choice of the output format for each step between raw, ANSI or HTML for example.

**Comment by bnjjj** [comment]
Ability to add option on step to tell what kind of format the logs are. In that case when in UI we display logs, we know the preferred format et so adapt our display

**Comment by yesnault** [comment]
close about display ascii.

@maxatome #3643 create for your request
