### ISSUE TITLE
fix(ui): Switching stage order using drag&drop do nothing

### ISSUE THREAD

**Issue by svandecappelle** [ovh/cds#3198]
When use drag&drop to change stage order the screen is refreshed and order didn't changed. 

![screenshot_2018-08-14 build-manager pipeline](https://user-images.githubusercontent.com/3873315/44084416-eda2161e-9fb6-11e8-9c04-aa559ff1932e.png)

Known workaround: Use edit-as-code.

**Comment by richardlt** [comment]
Can't reproduce, maybe fixed when upgrading dragula lib.
