### ISSUE TITLE
feat(payload): list dropdown

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#3244]
Hello,

In the payload modal, we have a dropdown to select a branch name.
Can we have the same for others variables? In the default payload, we could have a special format, to list all the possible values, and then displayed as a dropdown when we launch a wf?

Thx

**Comment by bnjjj** [comment]
is it linked to https://github.com/ovh/cds/issues/3218 ?

**Comment by blaryjp** [comment]
No, I want this for a custom variable of my payload.

**Comment by bnjjj** [comment]
seen together, your usage is linked to pipeline parameters
