### ISSUE TITLE
feature request: improve users mgmnt

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#3272]
Hello,

Open discussion: Is it possible to improve the users management?

Currently, it's annoying, because I can put only groups, not users. if I want to give rights to specific person, I need to create one group, with only one person. It means that I'll have a BUNCH of groups (with one or two persons) to maintain.

I think that a mgmnt like Bitbucket can be awesome: We set rights on the projects, and everything inherit from it. And we can "override" it by application, etc...

What do you think?

**Comment by sguiheux** [comment]
On our mind, right on application/pipeline has to be removed and inherit from project
We want to keep:
Read/Write on Project
Execution/Write on Workflow
Execution/Write on Environment

**Comment by yesnault** [comment]
```
REMOVE right on application/pipeline/environment
KEEP Read/Write on Project
KEEP Execution/Write on Workflow
ADD group RESTRICTION on pipeline (=node) inside a workflow (among the groups that have access to the workflow)
```
