### ISSUE TITLE
Enable to start CDS Hatchery Swarm hosted on Docker Swarm cluster

### ISSUE THREAD

**Issue by smramdani** [ovh/cds#3439]
Using the docker-compose file provided on CDS Github repo, I deployed CDS services on a Docker Swarm cluster based on 4 hosts (1 master and 3 workers, with 6Gb of RAM each) allocated using openstack driver on OVH public Cloud.
  
All CDS services work well (cds-db, cds-api, cds-ui, cds-cache) but I have problems with Hatchery Swarm (cds-hatchery-swarm).

It seams enable to connect to Docker daemon. With the following messages

When using UNIX socket
...
2018-10-10 17:38:56 [ERROR] hatchery> swarm> unable to ping docker host:Cannot connect to the Docker daemon at unix://var/run/docker.sock. Is the docker daemon running?
...

When using IP:PORT conf 
...
cds_cds-hatchery-swarm.1.wcvvtvawgr2y@docker-swarm-master    | 2018-10-10 17:56:02 [ERROR] hatchery> swarm> unable to ping docker host:Get http://[my-swarm-master-ip]:2376/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
cds_cds-hatchery-swarm.1.wcvvtvawgr2y@docker-swarm-master    | * Are you trying to connect to a TLS-enabled daemon without TLS?
cds_cds-hatchery-swarm.1.wcvvtvawgr2y@docker-swarm-master    | 2018-10-10 17:55:56 [ERROR] context canceled
...

Can you give me any advice please ?

My full docker-compose is attached 
[docker-compose-swarm-cds 2.yml.txt](https://github.com/ovh/cds/files/2465900/docker-compose-swarm-cds.2.yml.txt)

**Comment by yesnault** [comment]
Hi,
Did you export HOSTNAME before launching docker-swarm ?
```
host:Get http://:2376/_ping 
```
Seems not with this log.

You can comment the line with Volume : ` - /var/run/docker.sock:/var/run/docker.sock` and use only DOCKER_HOST.

Notice that this docker-compose.yml is or test purpose. For a prod environment, you should consider using a managed db for example.

**Comment by smramdani** [comment]
Hi,

Sorry for misleading log sample.
In fact, I have replaced (;-) my swarm master IP address by a hint [my-swarm-master-ip]
with "<" and ">" in place "[" and "]", that unfortunately hidden it (as a bad HTML tag !!).
I have edited the log since to fix that ;)

Yes, I have set the $HOSTNAME env variable (with my swarm master IP) and set the docker env as DOCKER_HOST: tcp://${HOSTNAME}:2376. The value is well passed to CDS and have the right value in the logs. But without succeeding to connect to Docker.

I tried other port values as 2375 and 2377, without success !!
I tested also without the Volume setting (- /var/run/docker.sock:/var/run/docker.sock) 
I have some security rules set, but all ports (1:65535) are open between the swarm hosts and with my local network.

Any other idea ?
Yes, I am just testing with docker compose and docker swarm, production is for later.
Thanks for your help!

**Comment by yesnault** [comment]
hatchery docker swarm need an access to docker API. Docker API have to be configured with DOCKER_HOST variable.

So, if you want to use `DOCKER_HOST= tcp://1.2.3.4:2376`, Docker have to listen on 2376 on `1.2.3.4`

If you have  access to docker daemon, you can try `-H tcp://1.2.3.4:2375` (replace `1.2.3.4` with your ip or 0.0.0.0 to listen all interfaces - beware, this expose your docker api to everybody, be ensure to do that is a private network)

If you use the socket, you have to run CDS Hatchery Swarm on the same host as docker.

If you are on a OSx, please read: https://github.com/ovh/cds/blob/master/docker-compose.yml#L74 

Feel free to come on https://gitter.im/ovh-cds/Lobby for any question, it will be faster to debug with you.
