### ISSUE TITLE
feature: find all pipelines that use a particular worker model

### ISSUE THREAD

**Issue by svandecappelle** [ovh/cds#3521]
Aim: found obsoletes workers and prepare actions to migrates them to newest version of binaries installed into a worker

Solution: It could be nice to have a screen or cli command to get all pipelines that use a certain type of model worker. Migration to other worker model would be really easy if we can identify them. 

Thanks =)

**Comment by yesnault** [comment]
it's available !

/ui/settings/worker-model/your-worker-model -> select usage (on the bottom for now)
