### ISSUE TITLE
[Feature request] task swift_upload

### ISSUE THREAD

**Issue by miton18** [ovh/cds#3551]
I'm aware of `artifact_upload` and `artifact_download` tasks. It seems they can't answer my use case.

Have you ever think about tasks `swift_upload` and `swift_download`? This can allow users to store artifacts and other in their own object storage not CDS one.

**Comment by sguiheux** [comment]
We thought about adding a storage platform: users will save their storage url/credentials. It will override artifact_upload/ artifact-download.

But maybe it will be faster to create a plugin/action to upload on your swift instead of waiting for this feature

**Comment by yesnault** [comment]
@miton18 we'll see to implement that soon, we need it for Nexus platform too.

**Comment by sguiheux** [comment]
And maybe for deb package too

**Comment by miton18** [comment]
Hi guys ! any news on the feature ?

**Comment by yesnault** [comment]
@miton18 dev on it starting this week.

**Comment by yesnault** [comment]
wip on https://github.com/ovh/cds/pull/3900

**Comment by yesnault** [comment]
#3900 merged
