### ISSUE TITLE
bug: requirements are not synchronized

### ISSUE THREAD

**Issue by landru29** [ovh/cds#3590]
Requirements are not synchronized when pushing the button "Synchronize workflow" on workflow relaunch

**Comment by yesnault** [comment]
seems be fixed, can't reproduce with type binaries at least

**Comment by bnjjj** [comment]
Found a bug when you have a model requirement with a variable from project like {{.cds.proj.pusher}}-builder-stretch-amd64 the requirement is not updated

**Comment by bnjjj** [comment]
add a documentation about the action on the UI. In fact we don't resynchronise the project variables
