### ISSUE TITLE
Different behavior for pip params between 2 process

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#3639]
Difference between here https://github.com/ovh/cds/blob/master/engine/api/workflow/process.go#L634

and here https://github.com/ovh/cds/blob/master/engine/api/workflow/process_node.go#L204

I thought it weird. Is it normal ? @sguiheux

**Comment by sguiheux** [comment]
I think L204 must stay like this, and the merge between pip param and node pip params must but done around here: https://github.com/ovh/cds/blob/master/engine/api/workflow/process_node.go#L120

**Comment by yesnault** [comment]
fixed with https://github.com/ovh/cds/commit/267f703ba0f91afacce7bc6e66fe75a89fda978d
