### ISSUE TITLE
Serve Static Files with a fix url

### ISSUE THREAD

**Issue by ticapix** [ovh/cds#3657]
Hi,

As a user consuming the files generated by a CDS pipeline, is it possible to configure an alias that will point to the latest static-files deployed by https://ovh.github.io/cds/workflows/pipelines/actions/builtin/serve-static-files/ ?

Thanks,

**Comment by yesnault** [comment]
we can add a attribute as:

static-key : {{.git.branch}}

To have a url as:
https://..../projectname/..workflow-name/node-name/staticfile/{{.git.branch}}
