### ISSUE TITLE
outgoing hooks - variables are not passed into payload

### ISSUE THREAD

**Issue by svandecappelle** [ovh/cds#3718]
Hello team CDS,

When trying to call an outgoing hook with this payload: 
```
{
  "git.branch": "{{.git.branch}}",
  "git.hash": "{{.git.hash}}"
}
``` 

tried with values: `{{.git.branch}}`, `{{.workflow.root.git.branch}}`

## Outgoing hook
The value is not send correctly rewritten to the called workflow, see capture.
![screenshot_2018-12-11 all_functionnal_tests workflow](https://user-images.githubusercontent.com/3873315/49818372-d4050d00-fd72-11e8-8c7a-a382e8832b62.png)

## Outgoing workflow
![screenshot_2018-12-11 pipeline test-cypress 15 git branch ux-manager-cloud-ftests](https://user-images.githubusercontent.com/3873315/49818356-cc456880-fd72-11e8-81f7-bc64e8fc871e.png)

**Comment by yesnault** [comment]
fixed
