### ISSUE TITLE
Unit tests are not more pushed to application view

### ISSUE THREAD

**Issue by svandecappelle** [ovh/cds#3719]
When I use the Junit plugin to push results.xml to application state, it show no errors but tests are not displayed into application view.

## Into build logs: 
![screenshot_2018-12-12 pipeline test-cypress 20 feat debug_logs_by_env ux-manager-cloud-ftests](https://user-images.githubusercontent.com/3873315/49862761-2855ce80-fdff-11e8-8bfc-bceb6bac6fc9.png)

## Into "Test" tab
![screenshot_2018-12-12 pipeline test-cypress 20 ux-manager-cloud-ftests](https://user-images.githubusercontent.com/3873315/49862791-36a3ea80-fdff-11e8-954a-3cd240074dbe.png)

## Into "Application" view
![screenshot_2018-12-12 manager-cloud application](https://user-images.githubusercontent.com/3873315/49862811-428fac80-fdff-11e8-8718-0f1e75de0e7a.png)

**Comment by sguiheux** [comment]
Metrics ( UnitTest, Vulnerabilities, Code coverage) are only pushed on default branch.

I notice just one bug here:
https://github.com/ovh/cds/blob/master/engine/elasticsearch/elasticsearch_handlers.go#L84

It should me false .  It's the parameter for ascending

**Comment by fsamin** [comment]
fixed on #3728
