### ISSUE TITLE
fix(wf): Impossible to create a workflow using template and a VCS

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#3750]
Hello,

I've created a workflow template, but it's impossible to create a workflow using it:
The list of repositories is empty - see screenshot.

https://plik.root.gg/file/IYNAByEQwQChTYFH/A7Bego7dVNnOLtOx/screenshot-cds-2018.12.19-10-39-45.png

I tried to unlink/relink the VCS, same problem.

Thx

**Comment by richardlt** [comment]
This is a ui issue, the repository manager you are using contains a lot of repositories that you can see.
The list is too long to render properly. We will fix this.

**Comment by yesnault** [comment]
done
