### ISSUE TITLE
fix(ui): edit as code worker model with a non-admin user

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3819]
<img width="1307" alt="capture d ecran 2019-01-05 a 11 45 50" src="https://user-images.githubusercontent.com/395454/50723535-895f8200-10df-11e9-907f-8609134a7136.png">

**Comment by bnjjj** [comment]
solution: same as UI if no shell and cmd are written explicitly then do not update existing shell and cmd. Same for export, do not export if not admin and not in restricted mode
