### ISSUE TITLE
fix(ui): run a pipeline after a join

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#3853]
![screen shot 2019-01-15 at 11 42 06](https://user-images.githubusercontent.com/684151/51175636-28903080-18bb-11e9-9a56-ff7b81fcab0e.png)
![screen shot 2019-01-15 at 11 42 21](https://user-images.githubusercontent.com/684151/51175651-2fb73e80-18bb-11e9-9d0a-0b0025c2db18.png)
![screen shot 2019-01-15 at 11 42 38](https://user-images.githubusercontent.com/684151/51175664-3e9df100-18bb-11e9-9672-c05772c0b155.png)
![screen shot 2019-01-15 at 11 42 59](https://user-images.githubusercontent.com/684151/51175682-49f11c80-18bb-11e9-9e14-0bcba13cd361.png)
![screen shot 2019-01-15 at 11 43 54](https://user-images.githubusercontent.com/684151/51175695-507f9400-18bb-11e9-9da8-cc349a1060a6.png)

**Comment by sguiheux** [comment]
Is it really a bug ? Do you have a run condition cds.manual on your join ?
You cannot run the pipeline because you have to run the join.
