### ISSUE TITLE
403 Forbidden when worker tries to update step result

### ISSUE THREAD

**Issue by DoronCohen** [ovh/cds#3963]
Hi,

I get ```[WARN] updateStepStatus> Cannot send step 0 result: HTTP 403 err: forbidden - try: 1 - new try in 15s``` when running a job on a local worker. the worker has a token which I generated with ```./cdsctl token generate shared.infra persistent```.

Am I doing anything wrong? It is also extremely weird that the worker can fetch the job but not report it's results. unless I am missing something, if it can't report the results, it shouldn't allow the worker to be assigned for this job.

**Comment by yesnault** [comment]
FYI: Running a standalone worker will be deprecated in few weeks.

For starting local workers, you can run:

```
engine start hatchery:local
```

You can use the flag `--config conf.toml` for configuration, conf.toml can be generated with `engine config new hatchery:local`.

**Comment by DoronCohen** [comment]
Thanks for the response. What is the `engine` CLI? Where should I find it? I ran CDS using the docker compose method.

**Comment by yesnault** [comment]
engine is the CDS binary wich contains all services: api, hatcheries, vcs, etc... You can choose to run all services `engine start` or just some services: `engine start api vcs`. You can find it on CDS Release https://github.com/ovh/cds/releases

If you use docker-compose, there a the hatchery local configured `docker-compose up cds-hatchery-local `
