### ISSUE TITLE
docker compose filed

### ISSUE THREAD

**Issue by chennqqi** [ovh/cds#3966]
command:
docker-compose up -d

error message:

> inotify@1.4.6 install /home/d33d33/metronome-ui/node_modules/inotify
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.12.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v5.12.0/node-v5.12.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v5.12.0/node-v5.12.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v5.12.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v5.12.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/d33d33/metronome-ui/node_modules/inotify/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/5.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/5.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/d33d33/metronome-ui/node_modules/inotify',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: Entering directory '/home/d33d33/metronome-ui/node_modules/inotify/build'
gyp info spawn make
  CXX(target) Release/obj.target/inotify/src/bindings.o
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
Killed
ERROR: Service 'ui' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 137

**Comment by yesnault** [comment]
your issue is not about cds, but about https://github.com/ovh/metronome-ui, please open this issue on this repo.

About docker-compose on CDS: please read https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/

**Comment by chennqqi** [comment]
sorry...
