### ISSUE TITLE
Add a way to have a "teardown pipeline"

### ISSUE THREAD

**Issue by skeetmtp** [ovh/cds#3985]
A pipeline run even if previous pipelines have failed.
Useful if you have a set-up pipeline that spawn things and you absolutely need to run a clean-up phase to not leak resouces

**Comment by yesnault** [comment]
you can do it with Run Conditions on cds.status. Default condition is cds.status = Success, but you can delete it.

**Comment by yesnault** [comment]
BTW: run conditions on stage will be improved: https://github.com/ovh/cds/issues/1949
