### ISSUE TITLE
Feature request: add support of arm64 in CDS release

### ISSUE THREAD

**Issue by dgoujard** [ovh/cds#4009]
Hello,

I would like to know if you plan to release arm64 versions of binary as you do for arm ? 
I think it could be compiled from source with go, I didn’t tried yet.

Thank

**Comment by richardlt** [comment]
Hi,
This is something we can do by adding a new arch in our makefile. 
What's the target platform/os you are planning to use ?
I used to run cds engine on a PI3 with Raspbian (32bit) it worked well :)

**Comment by dgoujard** [comment]
Hello,

I’m using Scaleway server in arm64 so the regular arm version didn’t work.
I using this server for my custom deployment system witch is fare less ambitious than CDS (one api and N workers witch spawn docker container for jobs (bash script))

Envoyé de mon iPhone

**Comment by yesnault** [comment]
@dgoujard planned for next release
