### ISSUE TITLE
UX - Add github to repository manager

### ISSUE THREAD

**Issue by tsupertramp** [ovh/cds#4022]
I am stuck under
"Link to a repository manager"
in project settings.

I always get an empty list there.

![image](https://user-images.githubusercontent.com/8327755/54138609-1c8aa000-4420-11e9-9d18-9be144b851d9.png)

Tried to configure "oauth apps" / "Github Apps" as developer, then the same for company scope but nothing worked. I always restarted the API server.

Could you make a step by step guide with pictures or even better tell me where to debug? - API log is not showing anything helpful. Should it?

Is the vcs service needed for github integration? - So i need to name the service maybe? - Done this as well but still not working. I tried to add a URL, temporarily disabled firewall on server to ensure it has nothing to do with firewall.

Got really frustrated at this point. Let us fix this docs together. I PR it as soon as you explain it to me.

Greetings, Thomas

**Comment by tsupertramp** [comment]
Got it, of course after 5h trying to connect it. I get it 4 minutes afterwards!

Thought the vcs services will be started automatically with engine if i name it which seems to be not as expected.

Will PR some docs for other folks out there.

**Comment by tsupertramp** [comment]
Will keep this open till it is resolved in docs. I hope this is in your interest. Otherwise close it.

**Comment by yesnault** [comment]
Hi,

yes, it lacks clear documentation on the entire GitHub integration. There is a big refactor on documentation website, see https://github.com/ovh/cds/pull/3983 with a dedicated section on "Integrations". I'll add some doc about GitHub settings, then ping you for review if you have something else to add, if you are ok of course :)

**Comment by tsupertramp** [comment]
Thats awesome @yesnault 👍

**Comment by yesnault** [comment]
@tsupertramp PR about documentation refactor is almost ready. Doc about github is now here: https://github.com/ovh/cds/blob/f246b202d57f83af014cd87618c126227a8501d7/docs/content/docs/integrations/github.md I tell you when it's deployed (before Tuesday normally)

**Comment by tsupertramp** [comment]
Hey @yesnault - Its better but i am still missing e.g. webhook config.

So i guess the normal flow a user wants:
- Git push
- CDS builds something

The triggering through git push should happen as webhook. And here i am still missing the correct configuration or help. I would at least would like to have the link to webhook docs or something like that if it is a bigger topic.

I am still missing clear information about "You need oauth app" - Github application is just unclear - It could be a"Github app" or a "Oauth app". I mean the following "secrets" contain "oauth" and you could guess it but from user perspective it would be easier and personally it would have helped me to understand it immediately.

I am on vacation the next week. After my vacation i will check the updated docs and retry to configure ohvs.

**Comment by yesnault** [comment]
Ok, I see.
The complete flow is:
1/ (CDS Administrator) add configuration on CDS Configuration File
2/ (a user, which is admin on a CDS Project) link Project to GitHub (to delegate auth)
3/ (a user, allowed on a CDS Project) link a CDS Application to a repo (select the clone method: ssh/http)
4/ add a repository webhook on a workflow (this will automatically create a webhook on GitHub)
5/ run this workflow, use CheckoutApplication
6/ see the Workflow Status on your Commit on GitHub.

I'll try to explain clearly that on GitHub.md page

**Comment by yesnault** [comment]
@tsupertramp 

PR updated -> https://github.com/ovh/cds/blob/1fd99b968a222b8c726b17558fa340aa1b3dfe4d/docs/content/docs/integrations/github.md

Don't hesitate to comment the PR (typo or other things), this will be probably merged on monday now.

Notice: the markdown on documentation (hugo) is not well understand by GitHub. See screenshot:
![Uploading Capture d’écran 2019-03-23 à 15.35.07.png…]()

**Comment by yesnault** [comment]
doc deployed -> https://ovh.github.io/cds/docs/integrations/github/
