### ISSUE TITLE
Usage of Bitbucket Cloud

### ISSUE THREAD

**Issue by jwtea** [ovh/cds#4026]
Firstly thank you for the amazing work on this project. 
Is it possible to use a Bitbucket Cloud repository in the repository manager?
Thanks,
p.s Apologies if this isn't the correct place to ask

**Comment by fsamin** [comment]
Hi,
Thank you.
For the moment, only Bitbucket Server is supported, but it shouldn't be a big deal to support Bitbucket Cloud as well. 
I cant tell you when we would implement it, but we will track it here.

**Comment by jwtea** [comment]
Thanks for the quick reply @fsamin
Would you be open to a PR for this?

**Comment by fsamin** [comment]
@jwtea, Sure, we would be glad !

**Comment by akrock** [comment]
We are also currently looking into potentially using CDS to replace our CI/CD processes, and would need to get the Bitbucket Server support in place before we could make that transition.

**Comment by fsamin** [comment]
Hello @akrock, Bitbucket server is supported; Bitbucket cloud is not for the moment.

Don’t hesitate to ask us if you need some support to set up the right way.

**Comment by DoronCohen** [comment]
Hi, Is there any estimation on this feature? Is it being worked on?

**Comment by bnjjj** [comment]
FYI @DoronCohen @akrock and @jwtea I'm currently on it. Would made a PR next week and will be available in next release :)
