### ISSUE TITLE
The size of this git repository is huge

### ISSUE THREAD

**Issue by mvdan** [ovh/cds#4040]
I'm considering switching from Drone to CDS, as I've read a couple of blog posts and really like the background and design. Thanks for making this open source!

However, I was a bit surprised by the size when doing a git clone:

```
Receiving objects: 100% (182506/182506), 179.51 MiB | 5.04 MiB/s, done.
```

Running a shell script like the one [here](https://stackoverflow.com/a/14329983), we can see that this is almost entirely because of 50cbb8917b62927cde160b367ff94b3861c3befe, which added an 87MiB (!!!) file `engine/cds-engine-linux-amd64`, and deleted it in 36e87fb33e6a1b84fa1ce1b282c7629db289c076.

Here are the overall top 10 largest blobs, largest last, by their size in bytes:

```
2098078 docs/static/mermaid/mermaid.dev.js
2361685 vendor/github.com/pierrec/lz4/fuzz/lz4-fuzz.zip
3013376 docs/themes/docdock/exampleSite/content/shortcode/attachments.files/adivorciarsetoca00cape.pdf
3647211 vendor/golang.org/x/text/language/display/tables.go
4950165 vendor/golang.org/x/text/collate/tables.go
13268876 contrib/templates/cds-template-deploy-marathon-app/cds-template-deploy-marathon-app
13268876 contrib/templates/cds-template-deploy-marathon-app/cds-template-deploy-marathon-app
13291804 contrib/templates/cds-template-deploy-marathon-app/cds-template-deploy-marathon-app
15503348 contrib/grpcplugins/deployment/examples/plugin-hello/dist/deployment-plugin-hello-darwin-amd64
87657917 engine/cds-engine-linux-amd64
```

It looks like four other binaries were committed to master at some point under `contrib/`, weighing 13-15MiB, which have been deleted since.

It would also be nice to reduce the size impact of files like `mermaid.dev.js` and `lz4-fuzz.zip`, but their ~2MiB size is dwarfed by the ~140MiB in committed binaries.

I reckon this repository would go from a massive 180MiB to a reasonable 30MiB or less, if the history was rewritten to completely remove these binaries. It would be a bit painful to contributors and developers this one time, but long term it would make development and contribution much faster and easier.

Ideally, this change would be paired with a CI check (or a git pre-commit check?) to ensure that files larger than ~2MiB are never committed to master, even if they are reverted immediately after.

**Comment by mvdan** [comment]
The repository also has a large number of stale branches. It would be nice to clean those up too.

**Comment by richardlt** [comment]
Hi, thanks for this analyse. I totally agree that we need to clean the history.
This will requires a rewrite of the history since maybe [fbb9f686](https://github.com/ovh/cds/commit/fbb9f686) (to remove all files +10MiB).
We will find the right moment to do this, as soon as possible. We need to close some PRs before.

**Comment by mvdan** [comment]
I agree this should be coordinated to minimize the need to redo PRs. Ideally, you'd only be rewriting the history once, so you might as well take the time to do it right and clean up everything :)
