### ISSUE TITLE
kubernetes kubeconfig service account

### ISSUE THREAD

**Issue by BrendanBall** [ovh/cds#4123]
To deploy to k8s the documentation says: To let CDS spawn workers on your kubernetes cluster you need to copy your kubeconfig.yaml in the current directory.
This is not a normal thing to do when using k8s. I've never had to give a deployment my local kubeconfig.yaml which contains all my clusters and their access tokens.

Should you not be creating a k8s service account with the correct permissions instead and have cds use that?

**Comment by bnjjj** [comment]
I will check if it's possible. in fact I don't know if a lot of helm chart deploy a pod which also deploy himself other pods in the sames kubernetes cluster (as our hatchery do). In fact this kubeconfig.yaml is only useful to configure our kubernetes hatchery that will spawn workers (as pod) in your current kubernetes cluster.

**Comment by jseguillon** [comment]
Hi. My opinion on this : yes it's a problem if you need to put admin credential in config. *obvious*

Best practice I know : 
 - set a service account with limited access
 - set a sidecar kube-proxy that will ingest service account 
 - in cds, change kube-api URLs to point on the proxy port 

Its now (more or less) usual in helm charts to add an `extraContainers` value like in this [grafana](https://github.com/helm/charts/search?utf8=%E2%9C%93&q=extraContainers) chart, to handle this case. 

Some stack discsusion here  : https://stackoverflow.com/questions/32859242/kubernetes-link-a-pod-to-kube-proxy

**Comment by yesnault** [comment]
fix on master - associated to release 0.39.2
