### ISSUE TITLE
Bitbucket -  RepositoryWebHook fails on pull request merge.

### ISSUE THREAD

**Issue by lucassith** [ovh/cds#4160]
I am trying to start pipeline using RepositoryWebHook.

It works when the Bitbucket's webhook event is set to "Push". However I would like to start the pipeline on "Pull request" "Merged" event and if I configure it this way:

![image](https://user-images.githubusercontent.com/7236601/55615925-f642f080-5790-11e9-9905-fb12bcc18755.png)

the hook's log will display POST error "Repository manager not found. Cannot read request body"

![image](https://user-images.githubusercontent.com/7236601/55616010-25596200-5791-11e9-8598-42967452ab05.png)

![image](https://user-images.githubusercontent.com/7236601/55615994-18d50980-5791-11e9-9235-f43657f914fa.png).

Is it possible to start the pipeline on PR merge event? Or maybe I must use WebHook instead of RepositoryWebHook?

**Comment by bnjjj** [comment]
It's not yet implemented to choose on which event you can subscribe. For now only for push event. But if I have a good understanding of your use case. It should work only with the push event. Because when you merge after accepting a merge request I think bitbucket will send a push event. In our private bitbucket it works like this.

**Comment by lucassith** [comment]
@bnjjj it is true. I have configured to use "Push" event and it works similarly to "Merged" event if combined with the condition like `git.branch = master` but the downside is that it creates log entry for each push.

Anyway this software is great and for now I will Push event. Thank you.

**Comment by bnjjj** [comment]
It's in our roadmap to let users choose events to subscribe :)
