### ISSUE TITLE
fix(api): cannot run manually a ascode workflow

### ISSUE THREAD

**Issue by richardlt** [ovh/cds#4202]
For a workflow that was renamed in a branch, the run is successfully triggered by the repo webhook. But if we want to manually run the workflow for the same branch, we have an error.

![Capture d’écran 2019-04-19 à 13 53 22](https://user-images.githubusercontent.com/1819206/56423053-ab55cc80-62aa-11e9-961d-8692ede371e3.png)

**Comment by sguiheux** [comment]
Fixed
