### ISSUE TITLE
Izanami documentation

### ISSUE THREAD

**Issue by reynn** [ovh/cds#4208]
CDS offers an integration for Izanami for feature flipping but it seems to be undocumented as of right now. I think some information on how to setup Izanami and CDS would make this feature a lot easier to use if people had an easy reference for setup.

**Comment by yesnault** [comment]
The support of izanami is now removed (in the next release 0.48.0). The feature flipping mechanism is now completely integrated into CDS, cdsctl will allow you to manage them.

Btw, the feature flipping is useful for CDS core dev, as:
- enable full telemetry tracing for some CDS projects
- enable some new features into our production for some projects only
