### ISSUE TITLE
fix(api): TakeJob errors managements

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#4213]
If the takeJob is in error, probably the job is globally in error and should failed:

example: 

pprofLabel>recoverWrap>Handle>postTakeWorkflowJobHandler>takeJob>LoadSecrets>DecryptVCSStrategyPassword: internal server error (caused by: Cannot takeJob nodeJobRunID:4557567: Cannot load secrets: LoadSecrets> Cannot decrypt vcs configuration: EncryptVCSStrategyPassword> Unable to decoding password: illegal base64 data at input byte 8)

**Comment by richardlt** [comment]
pprofLabel>recoverWrap>Handle>postTakeWorkflowJobHandler>takeJob>LoadNodeJobRunKeys: internal server error (caused by: Cannot takeJob nodeJobRunID:4576384: Cannot load keys: LoadNodeJobRunKeys> Cannot decode env key env-env-ssh-********: illegal base64 data at input byte 0)

**Comment by yesnault** [comment]
There are now much more data on job info about that.
