### ISSUE TITLE
fix(api): migrate workflow as code failure

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#4219]
When I migrate a workflow as code, it fails with a poor error message : "unable to enable workflow as code", but the error in logs says:

Repositories> processPush> push cdsAsCode-1556111686> [1522a623-1630-41cc-b843-50a571929ad4] error fatal: remote error: Insufficient permissions

In fact the error should be : "oups, to forgot to add the ssh key on your repository"

**Comment by yesnault** [comment]
if the ssh key does not have te right access, the repositories service is like that:

```
On branch cdsAsCode-1566994048
nothing to commit, working directory clean
```

--> a manual run of workflow on master gives: 

```
⚠ An error has occured: fatal: ambiguous argument 'origin/cdsAsCode-1566994048': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]' (exit status 128).
```

--> if migrate as code failed, repo should be delete from repositories service
