### ISSUE TITLE
feat(hatchery/k8s): support of  imagePullSecrets in podSpec

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#4228]
Support imagePullSecrets in Spec: apiv1.PodSpec (kubernetes.go, func (h *HatcheryKubernetes) SpawnWorker)

doc: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod

**Comment by yesnault** [comment]
worker model configuration and/or k8s configuration

**Comment by bnjjj** [comment]
Add field on worker model. Boolean private registry. If it's private we indicate creds for this private registry
