### ISSUE TITLE
How to create Hatchery for Kubernetes

### ISSUE THREAD

**Issue by odedsCoolScripts** [ovh/cds#4262]
Hi Team,

I'm new to CDS and I need some help with my implementation, I'll explain my configuration and what I'm trying to achieve. 
Hopefully that a good explanation will be written in the documentation. 

Configuration:
1) I'm running Kuberentes on AWS EKS. The cluster functions as expected: running jobs, containers from private AWS registry, etc..
2) Installed CDS on K8s successfully, using the CDS repo, cloned to my Mac
3) In CDS UI, crated a workspace, pipline and inside a pipline created a job for CDS education.
4) Crated a worker model with image from our private ECR.
5) In my Mac, installed 'cdsctl', and connected successfully to my CDS. Verified with `cdsctl health status`

My issue:
As I understand from documentation, now it's time to create a Kubernetes hatchery:
https://ovh.github.io/cds/docs/integrations/kubernetes/kubernetes_compute/
It says that I need to:
1) paste the generated token (generated successfully) in a config that I really don't understand where is it located, I have config.toml file i the repo, here: $CDS_REPO_HOME/contrib/helm/cds/. but I'm it is it.
Another linked doc shows $PATH_TO_CDS, but still I don't know where is it located...
2) run 'engine start' from $PATH_TO_CDS. Same problem, don't know where it is.

I'll by happy for your help, 

Appreciate your work, 
Thanks,
Oded

**Comment by bnjjj** [comment]
Hello ! Do you install CDS on your AWS EKS with our helm or not ? When you make a kubectl get pods do you see a pod named hatchery... ? 

Is your private ECR accessible from you kubernetes cluster ? And do you need to be logged to pull your image on your private ECR ?

**Comment by odedsCoolScripts** [comment]
> Hello ! Did you install CDS on your AWS EKS with our helm or not ? When you make a kubectl get pods do you see a pod named hatchery... ?
> 
> Is your private ECR accessible from you kubernetes cluster ? And do you need to be logged to pull your image on your private ECR ?

Thanks a lot @bnjjj  

Sorry I forgot to mention that I installed CDS on my K8s with CDS helm chart of course. The installation worked like a charm! All deployments and services are up and running, no issues with that a lot. I can see hatchery pod of course:
<img width="664" alt="Screen Shot 2019-05-07 at 18 20 23" src="https://user-images.githubusercontent.com/41224938/57311842-1568d100-70f5-11e9-9df7-bfb24dbfff2a.png">

About the ECR accessibility -sure,I think I mentioned it above. My k8s cluster accesses the private ecr smoothly and run containers from images in that ECR. It connect with AWS-IAM role for the K8s worker nodes.
I assume that If CDS commands the k8s cluster to install a container from a certain image (with my ecr address), the cluster/cluster mgmt will handle this in a transparent way to CDS. right?

**Comment by bnjjj** [comment]
Ok as far as I understand your hatchery is correctly spawned but the issue is when your hatchery will spawn a worker in your kubernetes cluster it doesn't work. In fact as you use a private registry, CDS haven't this feature yet. But you're lucky because I'm currently working on this issue #4228 and this #4253 and I will open the pull-request in few days. I think with this feature you'll be able to specify credentials linked to your image in your private registry directly inside your worker model.

**Comment by odedsCoolScripts** [comment]
Thanks a lot!
Can you please provide some tips on how to log/debug running workflows? 
will `CDS_LOG_LEVEL=debug` help?  if so, where to put it? 
I see empty lists for the command:
```
$ cdsctl workflow logs list TPJOBS general-test-workflow 17
List logs files on workflow general-test-workflow run 17
```
