### ISSUE TITLE
fix(api): some errors occured when resync a ascode workflow run

### ISSUE THREAD

**Issue by richardlt** [ovh/cds#4273]
Message: pprofLabel>recoverWrap>Handle>resyncWorkflowRunHandler: Workflow node not found (caused by: Cannot resync pipelines)
Stack trace:
Cannot resync pipelines
github.com/ovh/cds/sdk.WrapError
	/go/src/github.com/ovh/cds/sdk/error.go:726
github.com/ovh/cds/engine/api.(*API).resyncWorkflowRunHandler.func1
	/go/src/github.com/ovh/cds/engine/api/workflow_run.go:272
github.com/ovh/cds/engine/api.(*Router).Handle.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:245
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:152
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/handlers/compress.go:143
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:89
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/mux/mux.go:114
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2774
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1878
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337%

**Comment by yesnault** [comment]
fixed
