### ISSUE TITLE
migrate to workflow as code causes crashes into UI and does nothing

### ISSUE THREAD

**Issue by svandecappelle** [ovh/cds#4297]
I'm trying to migrate a workflow as code but it clicking the 'Save' button closes the popup and console show a error stack trace. The pull request on repository is not created. There is not any calls into the 'network' tab

<img width="779" alt="Capture d’écran 2019-05-16 à 15 48 29" src="https://user-images.githubusercontent.com/3873315/57858932-42eb0400-77f2-11e9-9996-02c35675b4db.png">

**Comment by yesnault** [comment]
it's fixed
