### ISSUE TITLE
fix(api): pipeline not launched in specific case with mutex

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#4305]
When you have a mutex on a pipeline. Your workflow is already run but you want to re-run a pipeline with a mutex. In same time you have the same pipeline which is running in another run. Then workflow is marked in "Building" but pipeline status doesn't move and is not waiting for the release of mutex.

**Comment by yesnault** [comment]
can't reproduce with https://github.com/ovh/cds/pull/4726 and https://github.com/ovh/cds/pull/4718
