### ISSUE TITLE
CDS on K8s: 'Bad request'- unable to perform request on service cds-vcs

### ISSUE THREAD

**Issue by odedsCoolScripts** [ovh/cds#4319]
Hi Team,

I'm new to CDS and I need some help with my implementation, I'll explain my configuration and what I'm trying to achieve.
Hopefully that a good explanation will be written in the documentation.

Configuration:
1) I'm running Kuberentes on AWS EKS. The cluster functions as expected: running jobs, containers from private AWS registry, etc..
2) Installed CDS on K8s successfully, using the CDS repo and Helm, cloned to my Mac
3) In my Mac, installed 'cdsctl', and connected successfully to my CDS. Verified with cdsctl health status.
4) Connecting to Github process: 
Note:  The next steps are not described well enough in the documentation, because it's for Kuberentes in particular, I did what I understood (I used this guide: https://ovh.github.io/cds/docs/integrations/github/):
a) Create Oauth in my Github account, with the following data:
    - Homepage URL = http://<my cluster elb url prefix>.eu-west-1.elb.amazonaws.com
    - Authorization callback URL = http://<my cluster elb url prefix>.eu-west-1.elb.amazonaws.com/repositories_manager/oauth2/callback
    - application name: CDS-wekaio
b) Planted the clientID/secret in the <Helm directory>/config.toml, under [vcs.servers.Github.github] 
c) apiAuthSharedinfratoken, random token of 64 chars in planted in:
    1. <Helm directory>/values.yaml and the same under 
    2. <Helm directory>/config.toml, under [api.auth] for 'sharedInfraToken', under [hooks.api] for 'token' and under [vcs.api] for 'token'
d) Service name for vcs and hooks in <Helm directory>/config.tomel. I copied these name from my k8s service list (these services already existed and no need to create them from scratch, thanks to Helm)
    1. Under [vcs] for field 'name' (name = "cds-weka-cds-vcs")
    2. Under [hooks] for field 'name' (name = "cds-weka-cds-hooks")
e) Performed the 'Update' command in my Helm and verified the Pods vcs and hooks are updated (or restarted)
f) Created a project --> advanced tab --> 'Link to a repository manager' --> choose github and connect
g) Exactly as described in the guide, clicking on 'click here'--> redirct to github for app authorization --> confirmed 
h) This is where the problems begin:

The issue:
1) I redirected to some kind of a CDS blank page that have just the top menu (CDS icon, projects, Bookmarks, Create a project). All the rest is white blank.
2) I got no 'validation code'
3) When I go to the application page in that project, I get a red alert for wronk vcs request ![Screen Shot 2019-05-21 at 15 40 33](https://user-images.githubusercontent.com/41224938/58168073-17569680-7c96-11e9-9e54-1048eb9ac18b.png)
4) Logs taken from vcs pod:
  

```
2019-05-21 12:33:45 [WARN] pprofLabel>recoverWrap>Handle>getReposHandler: not authenticated (caused by: VCS> getReposHandler> Unable to get access token headers) error_uuid=ad1b4abe-7bc4-11e9-8c97-b6daefc6c5f9 method=GET request_uri=/vcs/github/repos stack_trace=VCS> getReposHandler> Unable to get access token headers
github.com/ovh/cds/sdk.WrapError
	/go/src/github.com/ovh/cds/sdk/error.go:726
github.com/ovh/cds/engine/vcs.(*Service).getReposHandler.func1
	/go/src/github.com/ovh/cds/engine/vcs/vcs_handlers.go:289
github.com/ovh/cds/engine/api.(*Router).Handle.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:245
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:152
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/handlers/compress.go:143
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
	/go/src/github.com/ovh/cds/engine/api/router.go:89
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1995
github.com/ovh/cds/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/mux/mux.go:114
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2774
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1878
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337 status=401
Logs from 5/21/19 12:27 PM to 5/21/19 12:33 PM UTC
```

**Comment by bnjjj** [comment]
Ok I think you should indicate this route in the Authorization callback URL on GitHub : `http://.eu-west-1.elb.amazonaws.com/cdsapi/repositories_manager/oauth2/callback` because with the helm configuration there is a proxypass for api which is prefixed by `/cdsapi`

By the way, the code is kind of a workaround if your api is not accessible from internet (which is not your case). But you can find this code in the URL that Github redirect you (in query parameters).

Last but not least, we encounter somme issues with helm, because in the helm features it won't let us keep some generated password for database for example. So when you make an `update` it's possible that you lost all your data :( . Yes it's very uncomfortable. We haven't find any solution for now and we track the issue on the helm repository (https://github.com/helm/helm/issues/3053). We will work on a better solution ASAP.

**Comment by odedsCoolScripts** [comment]
Thanks a lot!

I had to revoke all users' tokens and then added the /cdsapi prefix.

That worked!

Now I have another service error with which I'll open a new thread...
