### ISSUE TITLE
cdsctl user login remains always on the first login

### ISSUE THREAD

**Issue by tgatinea** [ovh/cds#4379]
I've created a user "admin" and then I log to CDS via:
./cdsctl login --api-url http://localhost:8081 -u admin

Then I've created a new user "admin2" and I logged to CDS via:
./cdsctl login --api-url http://localhost:8081 -u admin2

But "./cdsctl user me" remains to user "admin".
I expected to move to user "admin2". 
Maybe I miss a deconexion or logout.

In fact, I don't know how to change user.

**Comment by yesnault** [comment]
You don't have this behaviour? --> 
```
➜  cdsctl user me
email     admin2@localhost.local
fullname  admin2@localhost.local
url       http://localhost:8081
username  admin2
➜  cdsctl login --api-url http://localhost:8081 -u admin
CDS API URL: http://localhost:8081
Username: admin
Password:
          cdsctl: You didn't specify config file location; /Users/yesnault/.cdsrc will be used.
? File /Users/yesnault/.cdsrc exists, do you want to overwrite? Yes
➜  cdsctl user me
email     admin@localhost.local
fullname  admin
url       http://localhost:8081
username  admin
```

**Comment by tgatinea** [comment]
Hummm, that's strange, I've added CDS_VERBOSE=true in my commands:

tgatinea@PF1LMZLE:~/cdstest$ CDS_VERBOSE=true ./cdsctl login --api-url http://localhost:8081 -u admin2
Configuration loaded from /home/tgatinea/.cdsrc
CDS API URL: http://localhost:8081
Username: admin2
Password: 
          2019/06/17 10:07:29 Stream > context> X-B3-TraceId=<nil> X-B3-SpanId=<nil> X-B3-Sampled=<nil>
2019/06/17 10:07:29 setup tracing = false ({00000000000000000000000000000000 0000000000000000 0}) on request to http://localhost:8081/login
2019/06/17 10:07:29 ********REQUEST**********
2019/06/17 10:07:29 POST /login HTTP/1.1
Host: localhost:8081
User-Agent: CDS/sdk
Content-Length: 163
Connection: close
Content-Type: application/json
X-Requested-With: X-CDS-SDK
Accept-Encoding: gzip

{"username":"admin2","password":"6a75cf6da63d1d2f701905ef8d691ebec84fe8cd21962454a036b5617f27a31da8ed4521af0b50fc01eb3bd59cfb169318b3888fb4cf2b5af7528c85533c2d5e"}
2019/06/17 10:07:29 ********RESPONSE**********
2019/06/17 10:07:29 HTTP/1.1 200 OK
Connection: close
Access-Control-Allow-Headers: Accept, Origin, Referer, User-Agent, Content-Type, Authorization, Session-Token, Last-Event-Id, If-Modified-Since, Content-Disposition, X-B3-Traceid, X-B3-Spanid, X-B3-Sampled, X-Api-Workflow-As-Code, X-Api-Workflow-Id, X-Api-Workflow-Name
Access-Control-Allow-Methods: GET,OPTIONS,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Accept, Origin, Referer, User-Agent, Content-Type, Authorization, Session-Token, Last-Event-Id, ETag, Content-Disposition, X-B3-Traceid, X-B3-Spanid, X-B3-Sampled, X-Api-Workflow-As-Code, X-Api-Workflow-Id, X-Api-Workflow-Name
Content-Type: application/json
Date: Mon, 17 Jun 2019 08:07:29 GMT
Etag: 1560758849
Session-Token: 666a4242-d848-4bd7-9bab-681f8eda8b48
Vary: Accept-Encoding
X-Api-Nanoseconds-Time: 1560758849465807545
X-Api-Process-Time: 5201055
X-Api-Time: 2019-06-17T08:07:29Z

{"user":{"id":2,"username":"admin2","fullname":"admin2","email":"admin2@localhost.local","admin":false,"origin":"local","favorites":null,"permissions":{}},"token":"666a4242-d848-4bd7-9bab-681f8eda8b48"}
2019/06/17 10:07:29 **************************
2019/06/17 10:07:29 Response Body: {"user":{"id":2,"username":"admin2","fullname":"admin2","email":"admin2@localhost.local","admin":false,"origin":"local","favorites":null,"permissions":{}},"token":"666a4242-d848-4bd7-9bab-681f8eda8b48"}
cdsctl: You didn't specify config file location; /home/tgatinea/.cdsrc will be used.
? File /home/tgatinea/.cdsrc exists, do you want to overwrite? Yes

But I still have:
tgatinea@PF1LMZLE:~/cdstest$ CDS_VERBOSE=true ./cdsctl user me
Configuration loaded from /home/tgatinea/.cdsrc
2019/06/17 10:07:56 Stream > context> X-B3-TraceId=<nil> X-B3-SpanId=<nil> X-B3-Sampled=<nil>
2019/06/17 10:07:56 setup tracing = false ({00000000000000000000000000000000 0000000000000000 0}) on request to http://localhost:8081/user/admin
2019/06/17 10:07:56 ********REQUEST**********
2019/06/17 10:07:56 GET /user/admin HTTP/1.1
Host: localhost:8081
User-Agent: CDS/sdk
Authorization: Basic YWRtaW46Yjc3NTcyZjItODY2Yi00MjY2LWEwMjgtOWQ4M2I2ZWM0ZTA2
Connection: close
Content-Type: application/json
Session-Token: b77572f2-866b-4266-a028-9d83b6ec4e06
X-Requested-With: X-CDS-SDK
Accept-Encoding: gzip

2019/06/17 10:07:56 ********RESPONSE**********
2019/06/17 10:07:56 HTTP/1.1 200 OK
Connection: close
Access-Control-Allow-Headers: Accept, Origin, Referer, User-Agent, Content-Type, Authorization, Session-Token, Last-Event-Id, If-Modified-Since, Content-Disposition, X-B3-Traceid, X-B3-Spanid, X-B3-Sampled, X-Api-Workflow-As-Code, X-Api-Workflow-Id, X-Api-Workflow-Name
Access-Control-Allow-Methods: GET,OPTIONS,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Accept, Origin, Referer, User-Agent, Content-Type, Authorization, Session-Token, Last-Event-Id, ETag, Content-Disposition, X-B3-Traceid, X-B3-Spanid, X-B3-Sampled, X-Api-Workflow-As-Code, X-Api-Workflow-Id, X-Api-Workflow-Name
Content-Type: application/json
Date: Mon, 17 Jun 2019 08:07:56 GMT
Etag: 1560758876
Vary: Accept-Encoding
X-Api-Nanoseconds-Time: 1560758876406592527
X-Api-Process-Time: 60494227
X-Api-Time: 2019-06-17T08:07:56Z

{"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"groups":[{"id":2,"name":"cdsdemo"},{"id":3,"name":"FirstProject","admins":[{"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"origin":"local","favorites":null,"permissions":{"Groups":["FirstProject"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}]},{"id":1,"name":"shared.infra","admins":[{"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"origin":"local","favorites":null,"permissions":{"Groups":["shared.infra"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}]}],"origin":"local","favorites":null,"permissions":{"Groups":["shared.infra"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}
2019/06/17 10:07:56 **************************
2019/06/17 10:07:56 Response Body: {"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"groups":[{"id":2,"name":"cdsdemo"},{"id":3,"name":"FirstProject","admins":[{"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"origin":"local","favorites":null,"permissions":{"Groups":["FirstProject"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}]},{"id":1,"name":"shared.infra","admins":[{"id":1,"username":"admin","fullname":"admin","email":"admin@localhost.local","admin":true,"origin":"local","favorites":null,"permissions":{"Groups":["shared.infra"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}]}],"origin":"local","favorites":null,"permissions":{"Groups":["shared.infra"],"ProjectsPerm":{"DEMO":7},"WorkflowsPerm":{"DEMO/MyFirstWorkflow":7}}}
email     admin@localhost.local
fullname  admin
url       http://localhost:8081
username  admin

So it remains with user admin, while the new file .cdsrc is:
tgatinea@PF1LMZLE:~/cdstest$ cat ~/.cdsrc 
Host = "http://localhost:8081"
InsecureSkipVerifyTLS = false
Token = "xxxxxxxx"
User = "admin2"

I understood that cdsctl is based upon "Secret-tool (libsecret)", my configuration is:
tgatinea@PF1LMZLE:~/cdstest$ sudo apt list | grep secret-tool
libsecret-tools/disco 0.18.8-1 amd64
libsecret-tools/disco 0.18.8-1 i386

tgatinea@PF1LMZLE:~/cdstest$ sudo apt list | grep libsecret
libmoonshot1/disco 1.1.0+libsecret~1ubuntu1 amd64
libmoonshot1/disco 1.1.0+libsecret~1ubuntu1 i386
libsecret-1-0/disco,now 0.18.8-1 amd64  [installé, automatique]
libsecret-1-0/disco 0.18.8-1 i386
libsecret-1-dev/disco 0.18.8-1 amd64
libsecret-1-dev/disco 0.18.8-1 i386
libsecret-common/disco,disco,now 0.18.8-1 all  [installé, automatique]
libsecret-tools/disco 0.18.8-1 amd64
libsecret-tools/disco 0.18.8-1 i386
moonshot-ui-dev/disco 1.1.0+libsecret~1ubuntu1 amd64
moonshot-ui-dev/disco 1.1.0+libsecret~1ubuntu1 i386
moonshot-ui/disco 1.1.0+libsecret~1ubuntu1 amd64
moonshot-ui/disco 1.1.0+libsecret~1ubuntu1 i386

Could it be related to my secret-tool/libsecret config?

**Comment by tgatinea** [comment]
I guess that I've found the root cause.

In libsecret, I have 2 secrets related to the same attribute.server that is "http://localhost:8081" :

secret-tool search --all server http://localhost:8081

[/org/freedesktop/secrets/collection/login/13]
label = http://localhost:8081
secret = 7c46146e-bb9f-4963-a604-03ba37b51e7a
created = 2019-06-14 15:41:28
modified = 2019-06-17 15:51:15
schema = io.docker.Credentials
attribute.username = admin2
attribute.server = http://localhost:8081
attribute.docker_cli = 1
attribute.label = CDS Credentials

[/org/freedesktop/secrets/collection/login/12]
label = http://localhost:8081
secret = a92ff029-6f2c-4d71-9f79-2181938be939
created = 2019-06-14 12:31:57
modified = 2019-06-17 15:49:12
schema = io.docker.Credentials
attribute.username = admin
attribute.server = http://localhost:8081
attribute.docker_cli = 1
attribute.label = CDS Credentials

But your code in configstore_linux_amd-'.go line 31 recovers the secret attribute.server set to c.Host:
       username, token, err := keychain.GetSecret(c.Host)

This leads to call in my case secretservice_linux.go

It returns always the secret with username="admin" and secret="a92ff029-6f2c-4d71-9f79-2181938be939"

I guess that the behaviour may be first recover from file ~/.cdsrc the attribute.server+attribute.username and then recover from libsecret all secrets related to attribute.server and find the one related to attribute.username of ~/.cdsrc

**Comment by yesnault** [comment]
the PR https://github.com/ovh/cds/pull/4563 allows to store many username on same URL in your keychain.
With that, you will see in your keychain a serverURL=http://cdsapiurl/#username.

**Comment by yesnault** [comment]
PR closed. Will be developed over #4556 refactor with a cdsctl context switching

**Comment by yesnault** [comment]
fixed on https://github.com/ovh/cds/pull/4556
