### ISSUE TITLE
cdsctl: D-Bus error while login

### ISSUE THREAD

**Issue by Ble4Ch** [ovh/cds#4429]
Hi, 

I'd like to reopen an old issue (https://github.com/ovh/cds/issues/3962), cuz it's still happening. We've got a "Error: Cannot autolaunch D-Bus without X11 $DISPLAY" with x64 cdsctl, not with 386.

Using Last cds version for tests purpose, on a Debian Stretch and an Ubuntu Server 18.04.

On Debian with cdsctl-linux-amd64 : 

```
root@debian-chris:~/cds# /tmp/cds/download/cdsctl login --api-url http://localhost:8081 -u admin --verbose
Unable to load configuration /root/.cdsrc
CDS API URL: http://localhost:8081
Username: admin
Password:
cdsctl: You didn't specify config file location; /root/.cdsrc will be used.
? File /root/.cdsrc exists, do you want to overwrite? Yes
Error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

Same VM with cdsctl-linux-386 : 

```
root@debian-chris:/home/chris# ./cdsctl-linux-386 login --api-url http://localhost:8081 -u admin --verbose
Configuration loaded from /root/.cdsrc
CDS API URL: http://localhost:8081
Username: admin
Password:
cdsctl: You didn't specify config file location; /root/.cdsrc will be used.
? File /root/.cdsrc exists, do you want to overwrite? Yes
```

```
root@debian-chris:/home/chris# cat /etc/debian_version
9.8
```

_Originally posted by @Ble4Ch in https://github.com/ovh/cds/issues/3962#issuecomment-508755522_

**Comment by yesnault** [comment]
you need to have libsecret installed, you can try to install these packages: `dbus dbus-x11 xauth libgconf-2-4 libsecret-1-0 libsecret-1-dev`

**Comment by Ble4Ch** [comment]
Got these packages already installed : dbus, libsecret-1-0, xauth

I've just installed those : dbus-x11, libsecret-1-dev, libgconf-2-4. I've still got the D-Bus error.

I don't get why with 386 cdsctl is ok, but not with amd64 binary.

**Comment by yesnault** [comment]
386 version don't use libsecret to store secret.  
Do you have a x service installed on your host? If it's a server, you can use the nokeychain version or use Xvfb.

**Comment by Ble4Ch** [comment]
no x service installed. My purpose is to use it later on production servers, which will be available by ssh only. I'll check it out monday, have a nice weekend :)

**Comment by yesnault** [comment]
ok, on a prod server, two choice:
 - x server Xvfb, to use keychain to store secret
 - with no xserver -> take amd64 version with no keychain. It's available on release binaries

**Comment by cheapRoc** [comment]
I didn't understand the "keychain" and "no keychain" versions of the `cdsctl` binary until this post. It would be helpful if this landed in the official documentation somewhere.
