### ISSUE TITLE
feat(ui): Identify the deployed release in production

### ISSUE THREAD

**Issue by StevenLeRoux** [ovh/cds#4498]
Hi, 

We've talked how we could quickly identify a release running in production. Many approaches could be used, git tag, and only deploy on tag, etc... 

Nonetheless, I think using a small primitive in a workflow could simplify this a lot and enhance CDS experience. For example, Labels are already available for workflows. One could create this label from a running workflow or pipeline. 

This way, it's a generic solution that anyone can use. (when deploy has succeeded, I update the label with an available variable, e.g. : running_commit=29f928ca2, running_branch=fix_...)

While in UI, we gain an instant view of what's been deployed in production from CDS.

**Comment by yesnault** [comment]
It's already available. Here, a star for each run deployed in production.
![Capture d’écran 2019-10-21 à 17 26 52](https://user-images.githubusercontent.com/395454/67219265-08803580-f428-11e9-8627-8cc1a2c64d25.png)

The star is a 'tag' on run:
![Capture d’écran 2019-10-21 à 17 27 53](https://user-images.githubusercontent.com/395454/67219362-2baae500-f428-11e9-8643-0c5bee43390b.png)

you can create this tag with `worker tag` command. Example:
![Capture d’écran 2019-10-21 à 17 29 25](https://user-images.githubusercontent.com/395454/67219454-5d23b080-f428-11e9-9125-1e152fc0aacf.png)

and of course, you can filter on 'inprod' tag in the sidebar.

Feel free to reopen if needed
