### ISSUE TITLE
Gitlab integration issue

### ISSUE THREAD

**Issue by louis-gounot** [ovh/cds#4575]
Hello,

I'm trying to install CDS with Gitlab integration through Helm

Everything is working except Gitlab integration.

I get following errors in VCS pod : 
```
Reading configuration file config.toml
Starting service vcs
2019-09-02 08:44:12 [ERROR] vcs> Unable to register: Register: resource not found (caused by: resource not found)
Service has been stopped: vcs Register: resource not found (caused by: resource not found)
```

In API pod, I can see register call from VCS : 
```
2019-09-02 08:44:12 [WARN] resource not found error_uuid=d693341c-cd5d-11e9-b5c7-022f4a9ad168 method=POST request_uri=/ status=404
```

I followed official guide bu I'm a bit stuck from now on.

Regards

**Comment by louis-gounot** [comment]
Hello

My issue is due to ingress configuration with Helm.

https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

I had to update ingress definition in order for API service to be handled properly through Ingress.

By the way, is there any reason to access API through ingress instead of directly (helm is deploying in same namespace, so I don't understand why we should go through ingress instead of internal endpoint).

**Comment by yesnault** [comment]
We do not support ready to run helm chart anymore. closed by https://github.com/ovh/cds/pull/5046
