### ISSUE TITLE
CDS does not handle MS AD attributes

### ISSUE THREAD

**Issue by 0rzech** [ovh/cds#4579]
As of now (v 0.41.0), CDS hardcodes OpenLDAP attributes, eg `uid`, `givenName` etc. It would be good if CDS administrator was able to choose attribute names depending on target LDAP server.

**Comment by yesnault** [comment]
fixed on https://github.com/ovh/cds/pull/4556

**Comment by yesnault** [comment]
fixed on https://github.com/ovh/cds/releases/tag/0.44.0
