### ISSUE TITLE
Feature request: team repository from bitbucker cloud

### ISSUE THREAD

**Issue by Mualig** [ovh/cds#4581]
With version 0.41.0, bitbucket cloud integration works fine, but only user created repos are available to be linked to an application.

Can team repos be listed also ?

**Comment by bnjjj** [comment]
@Mualig I will check impacts and let you know any ETA

**Comment by bnjjj** [comment]
I made a PR for this missing feature. It will be available in the next release :) https://github.com/ovh/cds/pull/4583
