### ISSUE TITLE
How to properly configure and use GRPC plugins

### ISSUE THREAD

**Issue by abelidze** [ovh/cds#4606]
Hello,

I'm trying to use GRPC-plugins, but can't figure out what is wrong because I can't make them work.

My steps:

0. I've configured cds with `config.toml` and started cds-api, cds-ui, cds-hatchery-local in docker:
```
cds-hatchery_1         | Reading configuration file /app/config.toml
cds-hatchery_1         | Starting service hatchery:local
cds-hatchery_1         | 2019-09-16 03:07:43 [INFO] hatchery:local> Service registered
cds-hatchery_1         | 2019-09-16 03:07:43 [INFO] hatchery-local> Starting service hatchery-local (0.41.0+cds.10547)...
cds-hatchery_1         | 2019-09-16 03:07:43 [INFO] hatchery> Stats initialized on cds-hatchery-local
cds-hatchery_1         | 2019-09-16 03:07:43 [INFO] hatchery-local> Starting HTTP Server on port 8086
cds-api_1              | Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
cds-api_1              | Running hooks in /etc/ca-certificates/update.d....done.
cds-api_1              | Reading configuration file /app/config.toml
cds-api_1              | Starting service api
cds-api_1              | 2019-09-16 03:06:17 [INFO] Directory /app/keys has been created
cds-api_1              | 2019-09-16 03:06:17 [INFO] api> Service registered
cds-api_1              | 2019-09-16 03:06:17 [INFO] Starting CDS API Server 0.41.0+cds.10547
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing mail driver...
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing feature flipping with izanami 
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing local objectstore...
cds-api_1              | 2019-09-16 03:06:17 [INFO] ObjectStore> Initialize Filesystem driver on directory: /app/artifacts
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing database connection...
cds-api_1              | 2019-09-16 03:06:17 [INFO] Bootstrapping database...
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initialize> create token for shared.infra group
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing redis cache on cache:6379...
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing HTTP router
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing Events broker
cds-api_1              | 2019-09-16 03:06:17 [INFO] api> Stats initialized
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing Metrics
cds-api_1              | 2019-09-16 03:06:17 [INFO] api> Metrics initialized
cds-api_1              | 2019-09-16 03:06:17 [INFO] Initializing Authentication driver...
cds-api_1              | 2019-09-16 03:06:17 [INFO] Auth> Initializing driver (ldap)
cds-api_1              | 2019-09-16 03:06:17 [INFO] Auth> Connecting to session store
cds-api_1              | 2019-09-16 03:06:17 [INFO] Auth> Connecting to session store
cds-api_1              | 2019-09-16 03:06:17 [INFO] Auth> Preparing connection to LDAP server: myproject.com:636
cds-api_1              | 2019-09-16 03:06:17 [INFO] Auth> Connecting to LDAP server
cds-api_1              | 2019-09-16 03:06:18 [INFO] Initializing event broker...
cds-api_1              | 2019-09-16 03:06:18 [INFO] Initializing internal routines...
cds-api_1              | 2019-09-16 03:06:18 [INFO] Starting GRPC services on :8082
cds-api_1              | 2019-09-16 03:06:18 [INFO] Starting CDS API HTTP Server on :8081
```
1. I've successfully compiled `plugin-download` from `contrib/grpclugins`.
2. I've added it (plugin.yml) and its binary (amd64) via cdsctl:
```
# cdsctl admin plugins import plugin.yml
# cdsctl admin plugins binary-add plugin-download plugin-linux-amd64.yml download-linux-amd64
# cdsctl admin plugins list
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
|             AUTHOR             |          DESCRIPTION           | ID | INTEGRATION |      NAME       |  TYPE  |
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
| Benjamin COENEN                | This is a plugin to download   |  1 |             | plugin-download | action |
| <benjamin.coenen@corp.ovh.com> | file from URL                  |    |             |                 |        |
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
```
3. I've created a workflow / pipeline / app to test grpc plugin:
```
version: v1.0
name: build
jobs:
- job: test
  steps:
  - plugin-download:
      filepath: .
      url: '{{.cds.app.URL}}'
  - script:
    - ls -la
  requirements:
  - plugin: plugin-download
```
4. I've tried to run pipeline, but it fails with this log:
```
Starting step "/plugin-download-1"
Unable to start grpc plugin... Aborting (GoRoutine: internal server error (caused by: plugin:plugin-download unable to start GRPC plugin... Aborting: plugin:plugin-download error on ReadString(len buff 0, content: ): <nil>))
End of step "/plugin-download-1" [Fail] with reason: Unable to start grpc plugin... Aborting (GoRoutine: internal server error (caused by: plugin:plugin-download unable to start GRPC plugin... Aborting: plugin:plugin-download error on ReadString(len buff 0, content: ): <nil>))
```

This plugin is just an example because I have such problem with any grpc-plugin.
Can anyone suggest me am I missed something or don't understand?

There is my `config.toml`: [gist](https://gist.github.com/abelidze/492bc129641adda6e3eef1bd33fbffa7)

Also I can confirm that all ports in my `docker-compose.yml` is exposed correctly and each service has access to each other.

P.S> Thank you for this superior tool, it's really awesome!

**Comment by yesnault** [comment]
Hi @abelidze 

Can you show me the plugin.yml and plugin-linux-amd64.yml files?

You will find here https://gist.github.com/nledez/89a0f061d34556b38aaccea27e1c106e a gist for install plugins (version 0.36.1)

**Comment by abelidze** [comment]
@yesnault 
Yes, of course. Uploaded them to gist: [plugin-linux-amd64.yml](https://gist.github.com/abelidze/492bc129641adda6e3eef1bd33fbffa7#file-plugin-linux-amd64-yml) | [plugin.yml](https://gist.github.com/abelidze/492bc129641adda6e3eef1bd33fbffa7#file-plugin-yml)

About your link - yes, I did it in the same way, no difference.

Thank you for response.

**Comment by yesnault** [comment]
@abelidze sorry for delay. I try to reproduce.

you can try:
```bash
$ cd contrib/grpcplugins
$ make build download
$ make publish download
```
this use cdsctl to upload the plugin.

After this command, I have same as you:

```
$ cdsctl admin plugins list
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
|             AUTHOR             |          DESCRIPTION           | ID | INTEGRATION |      NAME       |  TYPE  |
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
| Benjamin COENEN                | This is a plugin to download   |  1 |             | plugin-download | action |
| <benjamin.coenen@corp.ovh.com> | file from URL                  |    |             |                 |        |
+--------------------------------+--------------------------------+----+-------------+-----------------+--------+
```

The pipeline used for test:

```yml
version: v1.0
name: my-pipeline
jobs:
- job: New Job
  steps:
  - plugin-download:
      filepath: FILES
      url: https://github.com/ovh/cds/releases/download/0.41.0/FILES
  - script:
    - ls -lart
  requirements:
  - plugin: plugin-download
```

Result:
<img width="956" alt="Capture d’écran 2019-09-23 à 22 04 23" src="https://user-images.githubusercontent.com/395454/65458554-1dc86b00-de4e-11e9-9aa9-11564ce3c434.png">

Can you check if plugin binaries are well stored on `/app/artifacts/` ?

**Comment by yesnault** [comment]
@abelidze you use a local hatchery or another? If it's a docker worker model, the docker image used is public? 
We don't have any issue known with plugin execution, btw, the root cause is perhaps on your worker model.

**Comment by abelidze** [comment]
@yesnault 
Thank you for your advices, but no way, they don't work for me :(

There're my artifacts:
```
$ ls -la /tmp/artifacts/
итого 56
drwxr-xr-x 14 root root 4096 Th09 24 14:36 .
drwxr-xr-x  5  777 root 4096 Th09 24 11:32 ..
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-darwin-386-darwin-386
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-darwin-amd64-darwin-amd64
drwxr-xr-x  2 root root 4096 Th09 24 14:36 download-freebsd-386-freebsd-386
drwxr-xr-x  2 root root 4096 Th09 24 14:36 download-freebsd-amd64-freebsd-amd64
drwxr-xr-x  2 root root 4096 Th09 24 14:36 download-freebsd-arm-freebsd-arm
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-linux-386-linux-386
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-linux-amd64-linux-amd64
drwxr-xr-x  2 root root 4096 Th09 24 14:36 download-linux-arm64-linux-arm64
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-linux-arm-linux-arm
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-windows-386.exe-windows-386
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-windows-amd64.exe-windows-amd64
drwxr-xr-x  2 root root 4096 Th09 24 14:35 download-windows-arm.exe-windows-arm
```
Each of these directories store executable as expected (?).

Following your instruction step by step I'm still facing a problem after I run workflow:
`plugin:plugin-download unable to start GRPC plugin... Aborting: plugin:plugin-download error on ReadString(len buff 0, content: ): <nil>`

About my environment:
I'm using local hatchery and everything about CDS is executed in VirtualBox/Ubuntu-16.04.1-x86_64. Could it be the cause of problem?
My VM is accessible from host and everything is working except GRPC. I don't think it's a problem with network configuration because api and hatchery are in the same network and I've checked that they can connect to each other.

I'll try to run CDS outside VM on my linux-server and leave a response here after that.

**Comment by yesnault** [comment]
@abelidze  "Each of these directories store executable as expected (?)." -> yes, it's expected. I'm curious about the result of your test outside the vm.

**Comment by abelidze** [comment]
@yesnault 
Okay, i've made it a try and receive this error again :(
```
Unable to start grpc plugin... Aborting (GoRoutine: internal server error (caused by: plugin:plugin-download unable to start GRPC plugin... Aborting: plugin:plugin-download error on ReadString(len buff 0, content: ): <nil>))
```
Plugin was built and published using make with this golang version:
```
$ go version
go version go1.12.7 linux/amd64
```
On that machine:
```
$ uname -a
Linux server 4.4.0-164-generic #192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Pipeline and config is same as previous used.

The last thing I can try is to download/build latest cds-engine and execute everything outside docker to be sure what happens exactly.

**Comment by abelidze** [comment]
I did some research and guess that problem can be caused by [this line](https://github.com/ovh/cds/blob/25b9e201b8e9ccef9b108a55ca59b628e59297f9/engine/hatchery/local/local.go#L143) because there're no `--grpc-api` argument passed.
And also I can't create worker model for local hatchery due to [this](https://github.com/ovh/cds/blob/25b9e201b8e9ccef9b108a55ca59b628e59297f9/sdk/worker_model.go#L147) (host is visible in UI, but it's not a valid type for worker model... it's strange decision).

I'm going to do some tests on it later and give you a feedback.

**Comment by yesnault** [comment]
@abelidze the local hatchery does not use a worker model. This hatchery use the "worker" binary only. When the job is analyzed, the hatchery checks if all prerequisites matches this worker environment (binaries in PATH, network, etc...). And you can't use a prerequisite "model" with a local hatchery.
About `--grpc-api`, it's really strange. It's not related to plugin communication and this option will be removed in the next three months.
When the worker is starting, it starts to download the plugin from API, then executes steps. Perhaps, the path used by worker to download and execute binary is not ok on your host, if TMPDIR does not allow to execute binary, the plugin will fail. You can customize this default value ($TMPDIR) to another, it's the `basedir` configuration key in `[hatchery:local]` section.

**Comment by yesnault** [comment]
flag --grpc-api on worker was removed on release 0.44.0.
Feel free to reopen this issue if needed.
