### ISSUE TITLE
fix(ui): load the integration when application is selected in the wizard pipeline attach

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#4698]
When you add a pipeline in your workflow. First you choose the pipeline, then you select the application. If you want to be able to select an integration you must click on next instead of tab `integration` on the left. A solution could be to load integrations or enable tab when an application is selected.

**Comment by sguiheux** [comment]
Are you on master?
I think it’s already fixed:  https://github.com/ovh/cds/commit/c75b9a8428d4f0ab6aaf89dc5e349fa68e79704b

**Comment by bnjjj** [comment]
need to check with @maximecaruchet

**Comment by maximecaruchet** [comment]
Yes it seems to be working now, thank you for fixing! :)

**Comment by bnjjj** [comment]
Feel free to reopen if it needs
