### ISSUE TITLE
Kill run when new run is triggered

### ISSUE THREAD

**Issue by marie-j** [ovh/cds#4702]
Hello, 

On some cases, some branches are repushed or merged into another branch, therefore another build is triggered but the previous launched one doesn't stop and has to be manually.

Would it make sense to add an option to stop automatically previous run on a branch if some actions are made (push, merge etc...) ?

**Comment by fsamin** [comment]
From a CI point of view, it is interesting to let all the run finish on all the branches, even if new commit have been pushed.
By the way, if you want you can do it with a few command with `cdsctl`.
