### ISSUE TITLE
feat(ui): expand logs and return to previous format

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#4728]
With a step containing many logs:
 - it's colored, until the user click on 'expand all logs'
 - after expand, it's not possible to return to previous format (with color and truncated logs at the middle).
possible to add an option to return to previous format?

**Comment by bnjjj** [comment]
In fact the option for colored logs is disabled when lines of logs > ... lines. It's mainly for performance concerns. So what is the behavior you want ? Turn back to the previous state without all lines but with color ? Or you want all lines and colors ?

**Comment by yesnault** [comment]
"Turn back to the previous state without all lines but with color ?" -> yep
"Or do you want all lines and colors" -> why not, but only if user click on one button for that
