### ISSUE TITLE
fix(worker): wait before all services are running

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#4735]
Example: I have a service for mysql which launch directly the container but before accepting connection could take some times. 

Idea: we could add parameter to service to let us know on which port listening before launch the worker ? Just an idea...

**Comment by yesnault** [comment]
it is as docker-compose, docker run the container, then the app is executed inside. The client (the cds job), needs to wait the mysql accepting connection before doing something. But checking that is something related to the service, it's not the same check for pg, for kafka, etc... Thus, this will be check by user itself.
