### ISSUE TITLE
can not use cdsctl command in Centos

### ISSUE THREAD

**Issue by willhope** [ovh/cds#4737]
[root@localhost ~]# ./cdsctl login --api-url http://localhost:8081 -u admin
CDS API URL: http://localhost:8081
Username: admin
Password:
          cdsctl: You didn't specify config file location; /root/.cdsrc will be used.
? File /root/.cdsrc exists, do you want to overwrite? Yes
Error: Cannot autolaunch D-Bus without X11 $DISPLAY
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

only support ubuntu?

**Comment by yesnault** [comment]
Hi @willhope,

It's not related to ubuntu or not, it's related to keychain.

If you want to use cdsctl on a host without keychain, you have to use the `-nokeychain` version; `cdsctl-linux-amd64-nokeychain`. You can pick it from latest release.

If you want to use keychain to store secret, you have to install libsecret on you host. You will probably need a X Server or something like Xvfb.

**Comment by willhope** [comment]
thanks

**Comment by willhope** [comment]
but i got another wrong when i run cdsctl
[root@localhost ~]# ./cdsctl workflow applyTemplate
? Found one CDS project 'DEMO - FirstProject'. Is it correct? Yes
? Choose the CDS template to apply: Demo workflow hello world (shared.infra/demo-workflow-hello-world)
? Give a valid name for the new generated workflow MyFirstWorkflow
? Push the generated workflow to the DEMO project Yes
Error(d61896dd-fd68-11e9-a1ef-0242ac120004): application name must respect '^[a-zA-Z0-9.-_-]{1,}$'

logs is 

cds-api_1             | unable to import workflow  status=400
cds-api_1             | 2019-11-02 12:03:52 [INFO] ParseAndImport>> Import workflow  in project DEMO (force=true)
cds-api_1             | 2019-11-02 12:03:52 [INFO] Parse>> Parse workflow  in project DEMO
cds-api_1             | 2019-11-02 12:03:52 [WARN] pprofLabel>recoverWrap>Handle>postWorkflowPushHandler>Push>ParseAndImport>Parse: application name must respect '^[a-zA-Z0-9.-_-]{1,}$' (caused by: unable to import workflow : Workflow name  do not respect pattern ^[a-zA-Z0-9._-]{1,}$) error_uuid=d61896dd-fd68-11e9-a1ef-0242ac120004 method=POST request_uri=/project/DEMO/push/workflows stack_trace=Workflow name  do not respect pattern ^[a-zA-Z0-9._-]{1,}$

i seems that it can not got my real input, but got " ", is it a bug ?

**Comment by yesnault** [comment]
@willhope issue created here https://github.com/ovh/cds/issues/4738
