### ISSUE TITLE
How to use with gitea

### ISSUE THREAD

**Issue by patcito** [ovh/cds#4742]
Hi,

Are there instructions somewhere on how I could use this with gitea and configure it with gitea oauth2? 

Thanks,

Patrick

**Comment by yesnault** [comment]
issue already opened: https://github.com/ovh/cds/issues/3974
Even if it's not built-in (hook creation, build status), you can use gitea with the plain GitClone action.

**Comment by petrukngantuk** [comment]
> issue already opened: #3974
> Even if it's not built-in (hook creation, build status), you can use gitea with the plain GitClone action.

you mean in the cds pipeline, to execute git clone to gitea repo?

**Comment by yesnault** [comment]
> you mean in the cds pipeline, to execute git clone to gitea repo?

yes, two choices:
 - step script, with a call to git clone command
 - step gitClone, with your gitea url in url attribute
