### ISSUE TITLE
workflow not shown when started; now have a "MsgWorkflowStarting" notif only

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#4760]
Hello,

Since few week, I've a new bug: when I start a workflow, it's not show. I've a "MsgWorkflowStarting" message instead. See screenshot. I need to refresh the page to see it.

https://plik.root.gg/#/?id=eMGzQZuw2Ee3HAy0

Thx

**Comment by yesnault** [comment]
fixed, feel free to reopen if needed
