### ISSUE TITLE
fix (ui): new pipeline -> refresh pipelines project

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#481]
steps:

1. Create new projet
2. Add app
3. Add pipeline
4. go go pipelines tab with refresh
5. new pipeline is not displayed (bug)
6. refresh
7. pipeline is displayed

**Comment by sguiheux** [comment]
It's not a bug, that is normal ( for now) that list is not updated.
Waiting api refacto on  lastModified date.

**Comment by fsamin** [comment]
cf #488

**Comment by sguiheux** [comment]
UI rework on all CDS resources:
* project
* pipeline
* application
* environment

**Comment by sguiheux** [comment]
done
