### ISSUE TITLE
rebase refactor/authentication before merge

### ISSUE THREAD

**Issue by richardlt** [ovh/cds#4843]
Some existing branches should be rebased on latest refactor/authentication code before merging refactor/authentication on master. Then it will be easier to rebase those branches on master :)

- [x] ascodeCoreMirrorHelp - @sguiheux  - OK
- [x] canvas-authen - @sguiheux - OK
- [x] e2eUI - @sguiheux - OK

- [x] feat_cdn - @bnjjj - CONFLICTS need rebase on refactor/authentication
- [x] feat_cdn_artifacts - @bnjjj - CONFLICTS need rebase on feat_cdn
- [x] feat_cdn_icons - @bnjjj - CONFLICTS need rebase on feat_cdn
- [x] asCodeEditPipeline- @sguiheux - CONFLICTS need rebase on refactor/authentication => rebased on a new branch asCodeEditPipelineRebased
- [x] websocket - @sguiheux  =>  all commits re-applied on a new branch from refactor:            websocketRebased

**Comment by sguiheux** [comment]
I can’t do rebase on websocket branch, to complex. @richardlt @fsamin   could you try ? All conflicts are about authentication.

If you’re not able to do it, I will create new branch and reapply each websocket commit.( From 12 of July To 29 of August)
