### ISSUE TITLE
Cannot connect to vcs service: Connection refused

### ISSUE THREAD

**Issue by gogogocduser** [ovh/cds#4849]
I get the error bellow while trying to link a GitHub repository

> wrong request (from: Unable to perform request on … perform request on service cds-vcs-github (vcs))

The docker compose is the same with the example `https://raw.githubusercontent.com/ovh/cds/master/docker-compose.yml`. Except the config for service **cds-ui**:

>  cds-ui:
    image: ovhcom/cds-engine:latest
    command: sh -c "/app/cds-engine-linux-amd64 start ui"
    environment:
      CDS_UI_HOOKSURL: http://cds-hooks:8083
      CDS_UI_NAME: cds-ui
      CDS_UI_API_TOKEN: 
      CDS_UI_API_HTTP_URL: http://cds-api:8081
    ports:
      - "8084:8080"
    links:
       - cds-api
       - cds-hooks

GitHub OAuth:
![image](https://user-images.githubusercontent.com/35250565/71615753-5ca45480-2be5-11ea-8fe9-c63accec5c57.png)

Log in server api:

> cds-api_1             | 2019-12-31 08:30:34 [WARN] pprofLabel>recoverWrap>Handle>getRepositoriesManagerHandler>LoadAll>DoJSONRequest>doJSONRequest>doRequest: wrong request (from: Unable to perform request on service cds-vcs-github (vcs)) (caused by: error: services.DoRequest> Request failed: Get http://localhost:8084/vcs: dial tcp 127.0.0.1:8084: connect: connection refused) error_uuid=d08c11d5-2ba7-11ea-855b-0242ac160004 method=GET request_uri=/repositories_manager stack_trace=Get http://localhost:8084/vcs: dial tcp 127.0.0.1:8084: connect: connection refused
cds-api_1             | services.DoRequest> Request failed
cds-api_1             | github.com/ovh/cds/sdk.WrapError
cds-api_1             |         /go/src/github.com/ovh/cds/sdk/error.go:759
cds-api_1             | github.com/ovh/cds/engine/api/services.doRequest
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/services/http.go:258
cds-api_1             | github.com/ovh/cds/engine/api/services.doJSONRequest
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/services/http.go:128
cds-api_1             | github.com/ovh/cds/engine/api/services.DoJSONRequest
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/services/http.go:101
cds-api_1             | github.com/ovh/cds/engine/api/repositoriesmanager.LoadAll
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/repositoriesmanager/repositories_manager.go:46
cds-api_1             | github.com/ovh/cds/engine/api.(*API).getRepositoriesManagerHandler.func1
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/repositories_manager.go:26
cds-api_1             | github.com/ovh/cds/engine/api.(*Router).Handle.func1
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/router.go:281
cds-api_1             | net/http.HandlerFunc.ServeHTTP
cds-api_1             |         /usr/local/go/src/net/http/server.go:1995
cds-api_1             | github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/router.go:155
cds-api_1             | net/http.HandlerFunc.ServeHTTP
cds-api_1             |         /usr/local/go/src/net/http/server.go:1995
cds-api_1             | github.com/ovh/cds/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1
cds-api_1             |         /go/src/github.com/ovh/cds/vendor/github.com/gorilla/handlers/compress.go:143
cds-api_1             | net/http.HandlerFunc.ServeHTTP
cds-api_1             |         /usr/local/go/src/net/http/server.go:1995
cds-api_1             | github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
cds-api_1             |         /go/src/github.com/ovh/cds/engine/api/router.go:92
cds-api_1             | net/http.HandlerFunc.ServeHTTP
cds-api_1             |         /usr/local/go/src/net/http/server.go:1995
cds-api_1             | github.com/ovh/cds/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
cds-api_1             |         /go/src/github.com/ovh/cds/vendor/github.com/gorilla/mux/mux.go:162
cds-api_1             | net/http.serverHandler.ServeHTTP
cds-api_1             |         /usr/local/go/src/net/http/server.go:2774
cds-api_1             | net/http.(*conn).serve
cds-api_1             |         /usr/local/go/src/net/http/server.go:1878
cds-api_1             | runtime.goexit
cds-api_1             |         /usr/local/go/src/runtime/asm_amd64.s:1337
cds-api_1             | error status=400
cds-api_1             | 2019-12-31 08:30:34 [INFO] [400] | GET     |    3.664374ms | /repositories_manager [api.(*API).getRepositoriesManagerHandler]

**Comment by yesnault** [comment]
Hi.

CDS APi tried to reach the vcs services, but `Get http://localhost:8084/vcs: dial tcp 127.0.0.1:8084: connect: connection refused `

Is the vcs is up and running and well reachable from API on this url? If you add the vcs service in the docker-compose, vcs url should be `cds-vcs:8084` or something else, where `cds-vcs` is the service name in docker-compose.yml file.

**Comment by gogogocduser** [comment]
Sorry for late response @yesnault , I didn't add `vcs-cds` service to the docker-compose. I just created an vcs-config.yml file and run it separately. Below is my vcs config, I just change the port from 8084 to 8100 as 8084 is for the cds-ui service.

> ######################
# CDS VCS Settings
#######################
[vcs]
  URL = "http://localhost:8100"

  # Name of this CDS VCS Service
  # Enter a name to enable this service
  name = "cds-vcs"

  [vcs.UI]

    [vcs.UI.http]
      url = "http://localhost:8084"

  ######################
  # CDS API Settings
  #######################
  [vcs.api]
    maxHeartbeatFailures = 10
    requestTimeout = 10
    token = "32856c4814344f18f363bee60eb33745ad39b81c341a75ba807113b0883839f1"

    [vcs.api.grpc]
      # insecure = false
      url = "http://localhost:8082"

    [vcs.api.http]
      # insecure = false
      url = "http://localhost:8081"

  ######################
  # CDS VCS Cache Settings
  #######################
  [vcs.cache]
    ttl = 60

    [vcs.cache.redis]

      # If your want to use a redis-sentinel based cluster, follow this syntax ! <clustername>@sentinel1:26379,sentinel2:26379sentinel3:26379
      host = "localhost:6379"
      password = "cds"

  ######################
  # CDS VCS HTTP Configuration
  #######################
  [vcs.http]

    # Listen address without port, example: 127.0.0.1
    # addr = ""
    port = 8100

  ######################
  # CDS VCS Server Settings
  #######################
  [vcs.servers]
...
    [vcs.servers.Github]

      # URL of this VCS Server
      url = "https://github.com"

      [vcs.servers.Github.github]

        # The URL for the GitHub API.
        apiUrl = "https://api.github.com"

        #######
        # CDS <-> Github. Documentation on https://ovh.github.io/cds/hosting/repositories-manager/github/
        ########
        # Github OAuth Application Client ID
        clientId = "20224a1562d981d4ff39"

        # Github OAuth Application Client Secret
        clientSecret = "c12f1163991e8a4d1d8dbc8c74e341d5383fad93"

        # Does polling is supported by VCS Server
        disablePolling = false

        # Does webhooks are supported by VCS Server
        disableWebHooks = false

        # If you want to have a reverse proxy url for your repository webhook, for example if you put https://myproxy.com it will generate a webhook URL like this https://myproxy.com/UUID_OF_YOUR_WEBHOOK
        # proxyWebhook = "https://myproxy.com"

        # optional, Github Token associated to username, used to add comment on Pull Request
        token = "545fb4c5b74b0f25ee0c99d6f318b96824e0d461"

        # optional. Github username, used to add comment on Pull Request on failed build.
        username = "gogogocduser"

        [vcs.servers.Github.github.Status]

          # Set to true if you don't want CDS to push statuses on the VCS server
          # disable = false

          # Set to true if you don't want CDS to push CDS URL in statuses on the VCS server
          # showDetail = false

...


Error log is still the same:
cds-api_1             | 2020-01-02 04:03:03 [WARN] ```
pprofLabel>recoverWrap>Handle>getRepositoriesManagerHandler>LoadAll>DoJSONRequest>doJSONRequest>doRequest: wrong request (from: Unable to perform request on service cds-vcs (vcs)) (caused by: error: services.DoRequest> Request failed: Get http://localhost:8100/vcs: dial tcp 127.0.0.1:8100: connect: connection refused) error_uuid=c650eb42-2d14-11ea-84fa-0242ac160004 method=GET request_uri=/repositories_manager stack_trace=Get http://localhost:8100/vcs: dial tcp 127.0.0.1:8100: connect: connection refused
cds-api_1             | services.DoRequest> Request failed
cds-api_1             | github.com/ovh/cds/sdk.WrapError
cds-api_1             |         /go/src/github.com/ovh/cds/sdk/error.go:759
cds-api_1             | github.com/ovh/cds/engine/api/services.doRequest
```

**Comment by yesnault** [comment]
@gogogocduser if you enter into the cds-api container, is the http://localhost:8100/vcs is reachable? If not, http://$HOSTNAME:8100 is reachable?

**Comment by gogogocduser** [comment]
@yesnault both are connection refused.

**Comment by yesnault** [comment]
@gogogocduser the next release will contains a cds-vcs inside the docker-compose.yml.
On your host, you have to put a VCS url reachable from you API container. Perhaps that the easiest way is to add a new service in the docker-compose file, cds-vcs, with the configuration stored as a volume.

**Comment by gogogocduser** [comment]
I changed the http://localhost:8100 to http://host-ip:8100m, it works as of now. Thank you so much @yesnault .
