### ISSUE TITLE
uVCS: authenticated error

### ISSUE THREAD

**Issue by sguiheux** [ovh/cds#4912]
It seems that this uservice lost connection with repository manager.

- build fails to start
- vcs status are not sent

A reboot of VCS uservice, fix the problem

`GoRoutine>postWorkflowRunHandler>initWorkflowRun>StartWorkflowRun>runFromHook>processWorkflowDataRun>processStartFromRootNode>processNodeRun>processNode>getVCSInfos>Commit>doJSONRequest: Repository manager authentication error, please unlink and relink your CDS Project to the repository manager (caused by: cannot get commit infos for XXXX/XXX <sha>: unable to find commit <sha> on repository XXX/XXXX from <repository>: not authenticated).`

`An error has occurred: not authenticated.`

**Comment by yesnault** [comment]
fixed, no more issue about that
