### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by DNeier** [ovh/cds#4942]
Following the instructions [here](https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/) and running into an issue on the step `docker-compose up --no-recreate cds-migrate`

![January-31-095157](https://user-images.githubusercontent.com/1977504/73553675-f4c57180-440f-11ea-9d2e-763b280aebae.png)

Any help would be greatly appreciated, thanks!

**Comment by yesnault** [comment]
oh, yes sorry about that.

Line 22 of docker-compose.yml -> you can replace
```yml
command: /app/cds-engine-linux-amd64 database upgrade --db-host cds-db --db-user cds --db-password cds --db-name cds --db-sslmode disable  --migrate-dir /app/sql
```

with:

```yml
command: /app/cds-engine-linux-amd64 database upgrade --db-host cds-db --db-user cds --db-password cds --db-name cds --db-sslmode disable  --migrate-dir /app
```

The next release (0.44.0) contains a whole refactor about this docker-compose.yml file, with the fix of course.
