### ISSUE TITLE
A few more helm thoughts/issues

### ISSUE THREAD

**Issue by sean-abbott** [ovh/cds#4961]
So this time I was able to get CDS up and running using helm. Hooray!

But, still some holdups.

I have to install this inside a private network, so I have to use a private loadbalancer. It's not clear that the API works vi the UI or is exposed to the loadbalancer in this case. I wasn't able to get that working (that I know of), and consequentially, i wasn't able to get github integration working, which pretty much stopped the whole experiment in it's tracks. 

You say the api may not be exposed to external traffic, but then the API is expected to be the receiving hook for github integrations? Is there a middle groud? A subset of the API that CAN be exposed via the ui frontend?

**Comment by sean-abbott** [comment]
Note I was able to get a private loadbalancer working by adding the aws private loadbalancer annotation to the ui-svc.yaml template.

**Comment by bnjjj** [comment]
I will check your issues, but about the configuration toml file you can edit this one https://github.com/ovh/cds/blob/master/contrib/helm/cds/config.toml it's used in the template, we put it in a helm secret to use it in different pods.

**Comment by sean-abbott** [comment]
So, this is more of a k8s / helm question so I understand if the answer is to RTFM, but is there a way to update that without re-deploying the chart? I obviously did my github integration after I installed the chart. Or update the secrets and restart the associated service?

**Comment by bnjjj** [comment]
To re-deploy a chart you can use `helm upgrade` but I prefer a fresh new install with a `helm delete --purge` and a `helm install`. Pay attention if you use the postgresql and redis database from the helm chart you will loose all your data. If you try to change directly with kubectl you'll have some issues when your pods will be restarting because secrets and changes won't be persisted.
