### ISSUE TITLE
cds ui will not start 

### ISSUE THREAD

**Issue by sergeyr87** [ovh/cds#4994]
hi 
getting the next error stuck

2020-02-20 21:51:22 [WARN] pprofLabel>compress>recoverWrap>Handle>postAuthBuiltinSigninHandler>LoadConsumerByID>getConsumer: resource not found (caused by: resource not found) error_uuid=22512001-542b-11ea-881c-0a7af96cee1f method=POST request_uri=/auth/consumer/builtin/signin stack_trace=resource not found
github.com/ovh/cds/sdk.WithStack
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/sdk/error.go:799
github.com/ovh/cds/engine/api/authentication.getConsumer
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/authentication/dao_consumer.go:59
github.com/ovh/cds/engine/api/authentication.LoadConsumerByID
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/authentication/dao_consumer.go:97
github.com/ovh/cds/engine/api.(*API).postAuthBuiltinSigninHandler.func1
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/auth_builtin.go:45
github.com/ovh/cds/engine/api.(*Router).Handle.func1
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:297
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:158
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/gorilla/handlers.CompressHandlerLevel.func1
        /go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20160816184729-a5775781a543/compress.go:143
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/ovh/cds/engine/api.(*Router).compress.func1
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:96
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:88
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
        /go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1890
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357 status=404

what am i missing?

**Comment by yesnault** [comment]
Hi @sergeyr87 
UI need a valid token to start. To validate the token, you have to register the admin user with the INIT_TOKEN.

```bash
$ engine start api --config my-config-file.toml
$ cdsctl signup --api-url=http://your-cds-api
$ # INIT_TOKEN is available (1 hour) in the my-config-file.toml. You ca regenerate it with the engine config init-token command
# check the api log or mail sent to verify, add the INIT_TOKEN variable 
$ INIT_TOKEN=XXXXXXX cdsctl signup verify --api-url http://your-cds-api
```

#5011 opened to let user admin signup and verify with the webui.
