### ISSUE TITLE
[User authentication] GitLab not working with custom endpoint

### ISSUE THREAD

**Issue by louis-gounot** [ovh/cds#5005]
If using a custom GitLab deployment (ie not gitlab.com), user info is fecthed from gitlab.com instead of url defined in configuration file (or environment variable).

In first analysis, gitlab Golang client is using default url (gitlab.com) in its OAuthClient (see [engine/api/authentication/gitlab/gitlab.go#L102](https://github.com/ovh/cds/blob/master/engine/api/authentication/gitlab/gitlab.go#L102))

`Client.SetBaseURL(d.url) ` should be called in addition.

**Comment by yesnault** [comment]
fix merged
