### ISSUE TITLE
cdsctl disconnect user

### ISSUE THREAD

**Issue by equals215** [ovh/cds#5047]
Hello,

I'm currently integrating CDS for my company needs, and after a first installation for testing purposes I've deleted the Docker compose stack to do a much cleaner install but cdsctl seems stuck and I cannot find the proper way to disconnect the cli tool>

**Comment by yesnault** [comment]
Hi @equals215 
"cdsctl seems stuck" I'm not sure to well understand. Is it stuck about signup, login to another CDS ?  What command do you want to execute ?

BTW, cdsctl creates a file .cdsrc in your home directory. If you use keychain, you have to delete the keychain entry cdsctl too.

**Comment by equals215** [comment]
Sorry, I misunderstood the documentation. Have a nice day.
