### ISSUE TITLE
Unexpected stdin input with a bash script as Job

### ISSUE THREAD

**Issue by ThomasGsp** [ovh/cds#5114]
Hello,

With a bash script as job, we have an stdin input (at least fd is open).

eg:
```bash 
echo "[ ! -t 0 ] && echo 'stdin has data' || echo 'stdin is empty'" > test.bash
# Should return "stdin is empty"
bash test.bash
# Should return "stdin has data"
bash test.bash < test.bash
```

Expected:
> 1 | [INFO] Starting step "Script"
> 2 | [INFO] stdin is empty
> 3 | [INFO] stdin has data

Returned:
> 1 | [INFO] Starting step "Script"
> 2 | [INFO] stdin has data
> 3 | [INFO] stdin has data

This empty input can generate issue with script able to catch and manage a stdin.

I did not try with python / others languages...

Regards,

Thomas

**Comment by fsamin** [comment]
Hi according to `man test`:
```
-t file_descriptor
                   True if the file whose file descriptor number is file_descriptor is open and is associated with a terminal.
```
It means that `[ -t 0 ]` tests if stdin has a file descriptor AND **if it's associated with a terminal**.

The way the scripts are executed by the CDS worker, the scripts will **never** have stdin (stderr or stdout) associated with a terminal. So `[ ! -t 0 ]` will always be true.
