### ISSUE TITLE
Update documentation to mention 9.6 database instead 9.5 

### ISSUE THREAD

**Issue by hdost** [ovh/cds#5243]
When trying to run through https://ovh.github.io/cds/hosting/ready-to-run/
➜  cds ./cds-engine database upgrade --db-host localhost --db-user cds --db-password cds --db-name cds --db-sslmode disable --db-port 5432 --migrate-dir sql 
There are 204 migrate files locally. Current engine needs 185 files
Error: pq: syntax error at or near "NOT" handling 183_drop_deprecated_user.sql

**Comment by yesnault** [comment]
@hdost what is your database version?

you need a postgres >= 9.6

**Comment by hdost** [comment]
That would do it then I guess. I’ve renamed the ticket.

**Comment by yesnault** [comment]
@hdost this message "There are 204 migrate files locally. Current engine needs 185 files
" --> your binary cds-engine is not uptodate, your version does not match with 204 files.

Thank you for report, we fix the doc
