### ISSUE TITLE
Issue while  deploying sprint-boot project  in  CDS pipeline 

### ISSUE THREAD

**Issue by shansclensky** [ovh/cds#5272]
Hi All,

I am trying to deploy spring-boot project in CDS pipeline, the job which contains deployment of spring-boot project is keeps on running , it is not able to execute the next step in the same job or next job. 
Please find the screenshots attached for reference((line number 7).
![deploying_Spring_boot_in_CDS](https://user-images.githubusercontent.com/37622385/85286814-f3750e00-b4b0-11ea-8b72-a11604b3ddb1.PNG)

Also I found that the same command has  been successfully executed in local machine. Please find supporting screenshot below:
![Spring_boot_project_in_CDS_Local_machine](https://user-images.githubusercontent.com/37622385/85287365-c6752b00-b4b1-11ea-8cab-8af49d89b3ab.png)
![Spring_boot_project_in_CDS_Local_machine_curl_cmd](https://user-images.githubusercontent.com/37622385/85287384-cd9c3900-b4b1-11ea-984c-2c4eeb13647a.png)

Just wanted to understand is something wrong with CDS pipeline i have configured which is not letting us to execute the deployment command.

**Comment by yesnault** [comment]
Hi @shansclensky 
You can't use the nohup ... & in a step, the job will be ended before running your mvnw spring-boot:run, with all subprocesses. You can't use a CDS Step to launch a process detached from the worker process.

**Comment by shansclensky** [comment]
Hi @yesnault 
Thank you for providing this information, in that case what can be used to run a process in the background in the job via CDS. In my case i need to spin up a spring boot web server. Is there any other feature/functionality in CDS which will help me in achieving this. Any guidance/suggestion will be really helpful.

**Comment by yesnault** [comment]
We have many use case where the builded image in the workflow is tested in the same workflow:
- run a docker or docker compose in the job, then test their app inside the job
- use the CDS Service Prerequisite (doc https://ovh.github.io/cds/docs/concepts/requirement/requirement_service/ ) to spawn a image docker at job startup, then call their app from the job.
