### ISSUE TITLE
Kafka integration with CDS failing

### ISSUE THREAD

**Issue by shansclensky** [ovh/cds#5307]
Hi All,
I am trying to integrate kafka with CDS, I have currently set up kafka in my host machine with single node in port 9092 as mentioned in official CDS documentation and also with CLI i am able to send and receive message but when I am trying to give the 
same configuration in CDS UI it is failing . I have attached the CDS UI screenshot and logs as well. Kindly let me know if i have missed out anything.
![Kafka_integration_error](https://user-images.githubusercontent.com/37622385/86906598-6af1a100-c131-11ea-910d-20ff27330c18.png)
![Kafka_integration_logs](https://user-images.githubusercontent.com/37622385/86906610-6f1dbe80-c131-11ea-85d1-6d0fbf1c82cf.png)

**Comment by yesnault** [comment]
your must set a topic.

```
if conf.BrokerAddresses == "" ||
		conf.User == "" ||
		conf.Password == "" ||
		conf.Topic == "" {
		return nil, fmt.Errorf("initKafka> Invalid Kafka Configuration")
	}
```

**Comment by shansclensky** [comment]
Thanks Yesnault, I have created a topic for Kafka integration however will check once again.

**Comment by shansclensky** [comment]
Hi @Yesnault,  as you can see in this screenshot we have set a topic and after that also we are getting the same error. Let me know if I have missed out anything in cofiguration.

![Kafka_integration_logs](https://user-images.githubusercontent.com/37622385/87000545-f5d6a800-c1d2-11ea-95b0-e6780a1ae3b3.png)
![server properties](https://user-images.githubusercontent.com/37622385/87000547-f66f3e80-c1d2-11ea-9b04-19c25e4072fa.PNG)
![Kafka_integration_error](https://user-images.githubusercontent.com/37622385/87000544-f40ce480-c1d2-11ea-8a15-7bf432753e43.PNG)

**Comment by yesnault** [comment]
did you try without `PLAINTEXT://` ? Should be only `localhost:9092`

**Comment by shansclensky** [comment]
Yes @yesnault I have tried without PLAINTEXT:// but the result is same. Please find the screenshot attached.
![kafka_error](https://user-images.githubusercontent.com/37622385/87123805-15d69c00-c2a5-11ea-92fd-505a9cfc7eb2.PNG)
![kafka_logs](https://user-images.githubusercontent.com/37622385/87123820-1c651380-c2a5-11ea-9e48-2753b49674b6.PNG)

Kindly let me know where i am going wrong.

**Comment by shansclensky** [comment]
at @yesnault  kindly request you to  re-open the ticket as it is not resolved it yet.

**Comment by yesnault** [comment]
This integration is heavily used on our production, this should be only a configuration mistake. Can you give me a `docker run kafka` configuration example to reproduce your case please? Ticket reopened until we will understand why it's not ok for you.

**Comment by shansclensky** [comment]
Hi @yesnault , I have installed cds using binaries I have not taken the docker approach. I am attaching the config files which i used for kafka integration setup. please find the attached server properties.
![cofig_files](https://user-images.githubusercontent.com/37622385/87419767-aee11c00-c5f1-11ea-83fb-47a425844b1b.PNG)
![server properties](https://user-images.githubusercontent.com/37622385/87419774-b274a300-c5f1-11ea-94af-e633d5385ccf.PNG)

**Comment by shansclensky** [comment]
Hi @yesnault is there any alternative approach i should take to resolve this or something is wrong with binary approach i have configured. Kindly let me know about this.

**Comment by yesnault** [comment]
You have to configure your kafka with user/password auth to read from your topic. Please see https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_plain.html

CDS can't read without a good user/password on a kafka topic, otherwise the error you have is visible in the logs.

**Comment by shansclensky** [comment]
okay thanks @yesnault , I  will go through the link you shared and will  try to reset the credentials for the kafka topic.

**Comment by yesnault** [comment]
@shansclensky CDS uses SASL and TLS enable to connect to kafka.

**Comment by shansclensky** [comment]
Hi  @yesnault  SASL is not working when configured , I  observed broker service when started in turn stops the kafka service.  I have attached the configuration file i have used
![image](https://user-images.githubusercontent.com/37622385/88157287-30573080-cc28-11ea-88e2-8000b09f082e.png) kindly go through and confirm if that is required configuration. With PLAINTEXT i was able to create consumer and producer and share messages within but with SASL I am unable to create broker server.

**Comment by yesnault** [comment]
So, this is definitively a kafka configuration issue. You have to have a kafka working with SASL/TLS to use it in CDS.
