### ISSUE TITLE
Kubernetes integration with CDS error

### ISSUE THREAD

**Issue by shansclensky** [ovh/cds#5329]
Hi all,

I am trying to integrate the Kubernetes with CDS, i am following the official documentation. I am getting an error while installing plugins relate to kubernetes, the log says that the unable to insert the plugin key violates unique story constraint . I have attached the error message.
![image](https://user-images.githubusercontent.com/37622385/87936318-40e49b00-cab0-11ea-91c2-28f4e13d962a.png) So i thought i will delete the plugin through cdsctl but only i can see ID and not the duplicate plugins listed . Please find below image.
![image](https://user-images.githubusercontent.com/37622385/87936965-6c1bba00-cab1-11ea-8547-460199f5e3d4.png)
Kindly let me know how can i see all those plugins and add or delete them so that i can resolve the issue.

**Comment by yesnault** [comment]
Hi @shansclensky you have an empty plugin with ID 2.

It'a a bug, cds should refuse an invalid format.
You have to remove invalid plugin, with this sql request:
```sql
delete from grpc_plugin where name = '';
```
then, confirm that cdsctl admin plugins list does not contain the invalid ID. 

Create the file plugin-kubernetes-deployment.yml :
```yml
name: plugin-kubernetes-deployment
type: integration-deploy_application
integration: Kubernetes
author: "OVH SAS"
description: "Kubernetes Deployment Plugin"
```

Create the plugin:

```bash
cdsctl admin plugins import plugin-kubernetes-deployment.yml
```

download cds-plugin-kubernetes-deployment-all.tar.gz from the latest release (0.47.0), unzip it, then import the binary
```bash
cdsctl admin plugins binary-add plugin-kubernetes-deployment plugin-kubernetes-deployment-linux-amd64.yml plugin-kubernetes-deployment-linux-amd64
```

Is it ok with that for you?

**Comment by shansclensky** [comment]
Hi @yesnault thanks for the detailed explanation, I was able to fix it!

**Comment by yesnault** [comment]
ok, I'll do a fix to avoid import an invalid plugin yml

**Comment by shansclensky** [comment]
Thanks @yesnault that will prevent people from facing the similar issue!
