### ISSUE TITLE
Typo in "Run with binaries" documentation

### ISSUE THREAD

**Issue by gsalingu** [ovh/cds#5342]
While booting my first CDS instance, and following the documentation available here: https://ovh.github.io/cds/hosting/ready-to-run/from-binaries/#prepare-database

I get the following error message when I run the command to prepare the database schema:

```
gsalingu@kwak:~/cds$ ./cds-engine database upgrade --db-host localhost --db-user cds --db-password ayato!42! --db-name cds --db-sslmode disable --db-port 5432 --migrate-dir sql/api
./cds-engine database upgrade --db-host localhost --db-user cds --db-password <PASSWORD> --db-name cds --db-sslmode disable --db-port 5432 --migrate-dir sql/api
Error: open sql/api: no such file or directory
gsalingu@kwak:~/cds$
```
Indeed there is no sql directory in there

```
gsalingu@kwak:~/cds/sql$ ls -lai | grep api
gsalingu@kwak:~/cds/sql$ 
```

Trimming the --migrate-dir option from the /api suffix will fix the issue

```
gsalingu@kwak:~/cds$ ./cds-engine database upgrade --db-host localhost --db-user cds --db-password <PASSWORD> --db-name cds --db-sslmode disable --db-port 5432 --migrate-dir sql
There are 209 migrate files locally. Current engine needs 209 files
```

**Comment by gsalingu** [comment]
https://github.com/ovh/cds/pull/5343

**Comment by yesnault** [comment]
Public documentation is now linked to the latest release. Doc on current master will be available from ui service in the next release.
