### ISSUE TITLE
Docker Compose Install "cdstest_cds-migrate_1 exited with code 1"

### ISSUE THREAD

**Issue by pierreyves258** [ovh/cds#5349]
Hi,

When i'm trying to install cds following this tutorial https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/
I'm getting stuck at the cds-migrate step

```
$ docker-compose up --no-recreate cds-migrate
cds-migrate_1         | Error: open /app/sql/api: no such file or directory
cds-migrate_1         |
cds-migrate_1         | Error: open /app/sql/cdn: no such file or directory
cds-migrate_1         |
cdstest_cds-migrate_1 exited with code 1
``` 

```
$ docker logs cdstest_cds-db-api_1
...
LOG:  database system was shut down at 2020-07-27 21:02:34 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "integration_model" does not exist at character 15
STATEMENT:  SELECT * from integration_model WHERE public = true AND integration_model.event = true
ERROR:  relation "cds_migration" does not exist at character 23
STATEMENT:  SELECT COUNT(id) FROM "cds_migration"
LOG:  could not receive data from client: Connection reset by peer
LOG:  unexpected EOF on client connection with an open transaction
```

The SQL error seem strange, do you have an idea ?

Regards

**Comment by mickaelmani** [comment]
+1

**Comment by reynn** [comment]
This seems to be because the Docker image was built without the directories so everything is just in the `/app/sql` folder and not broken out into `/app/sql/api` and `/app/sql/cdn` the `sql.tar.gz` in the releases seems to be the same way.

**Comment by mickaelmani** [comment]
Thanks for the workaround

**Comment by yesnault** [comment]
Hi all. The public documentation should contains only the latest release, at least. On the master branch, there is a new service under development (cdn), which needed a new database. We'll update the documentation packaging to take care about that.

**Comment by yesnault** [comment]
public documentation is now linked to the latest release
