### ISSUE TITLE
Mail notification and UTF-8 "Title"

### ISSUE THREAD

**Issue by maxatome** [ovh/cds#5351]
If an email notification is created with a Title containing UTF-8 chars, like:
```
[release 🚀] {{.git.message}}
```
the encoding is not declared in the Subject header, so the mail reader can not render it correctly:
```
[release ðŸš€] …
```
To avoid doing it by ourselves:
```
=?UTF-8?Q?[release =f0=9f=9a=80]?= {{.git.message}}
```
Shouldn't the mail subject be automatically encoded using RFC 2047 if an UTF-8 character is detected?

**Comment by yesnault** [comment]
On thunderbird: 
![x](https://user-images.githubusercontent.com/395454/94932923-ffb63180-04c9-11eb-8f01-b4af1c1203e9.png)

reopened
