### ISSUE TITLE
Worker models are not registered if they do not provide any Requirements

### ISSUE THREAD

**Issue by xtrochu** [ovh/cds#5411]
Using CDS Release 0.47, I had a lot of issue trying to add a new worker model. The system reported an "internal server error" but the hatchery was correctly starting the registering worker which seemed to perform its registration without error.

After following the code, I think I finally find out the issue, in `engine/api/worker/registration.go:114`
`
	//If the worker is registered for a model and it gave us BinaryCapabilities...
	if model != nil && spawnArgs.RegisterOnly && len(registrationForm.BinaryCapabilities) > 0 && spawnArgs.Model.ID != 0 {
		if err := workermodel.UpdateCapabilities(ctx, db, spawnArgs, registrationForm); err != nil {
			log.Error(ctx, "updateWorkerModelCapabilities> %v", err)
		}
		if err := workermodel.UpdateRegistration(ctx, db, store, spawnArgs.Model.ID); err != nil {
			log.Warning(ctx, "registerWorker> Unable to update registration: %s", err)
		}
	}
`

The test `len(registrationForm.BinaryCapabilities)` was failing because no declared binary could be found in the worker model. 

I was able to have the worker model register by adding a dummy Action with a requirement on a binary present in the model's container to have it register but it seems to me that it should not be mandatory to do so in order to register a worker model.

**Comment by fsamin** [comment]
thanks a lot for your investigation, the fix will be available in the next release
