### ISSUE TITLE
how to run it in win10 OS by binaries way?

### ISSUE THREAD

**Issue by YLQZ** [ovh/cds#5445]
export INIT_TOKEN=`./cds-engine config init-token --config conf.toml`  

this command is in linux OS ， how to do the same thing in win10 OS  and  next   start api ,  start ui; when start ui   there  said  Waiting for CDS API ，  is this because   export   command  ？   how to  run it  go on?

**Comment by yesnault** [comment]
Hi,

To start the ui, you need the API with engine.exe start api. Is your api running without any error (following this documentation https://ovh.github.io/cds/hosting/ready-to-run/from-binaries/) ?

About init token, you can try this:
in PowerShell:  `$env:INIT_TOKEN="the-init-token"`

in cmd: `set INIT_TOKEN=the-init-token`

with `the-init-token` containing the output the the `cds-engine.exe config init-token --config conf.toml`

**Comment by yesnault** [comment]
feel free to reopen if needed
