### ISSUE TITLE
UI - Subworkflow with parent sidebar

### ISSUE THREAD

**Issue by marie-j** [ovh/cds#5519]
Hello, 

When opening a linked workflow triggered by the open one by double clicking on the pipeline, the new workflow opens but with the parent sidebar instead of the current workflow's one. 

For example:
I'm on workflow A and I double click on a pipeline that leads me to workflow B. Instead of having the workflow B sidebar I'll have workflow A one 

Thanks

**Comment by fsamin** [comment]
i guess @sguiheux will have a look on this

**Comment by sguiheux** [comment]
already fixed
