### ISSUE TITLE
CDN Service

### ISSUE THREAD

**Issue by nevetS** [ovh/cds#5524]
I'm migrating my local config and deployment to Kubernetes.  There are some configuration settings related to CDN, that I don't see any detail about in the documentation.

```
  ###########################
  # CDN settings.
  ###########################
  [api.cdn]

    # Private URL for communication with API
    URL = "http://localhost:8089"

    # Name of this CDS CDN Service
    # Enter a name to enable this service
    name = "cds-cdn"

    # Public address to access to CDN HTTP server
    publicHTTP = ""

    # Public address to access to CDN TCP server
    publicTCP = ""

    ######################
    # CDS API Settings
    #######################
    [api.cdn.api]
      maxHeartbeatFailures = 10
      requestTimeout = 10
      token = "************"

      [api.cdn.api.http]
        insecure = false
        url = "http://localhost:8081"

    ######################
    # CDS CDN HTTP Configuration
    #######################
    [api.cdn.http]

      # Listen address without port, example: 127.0.0.1
      # addr = ""
      port = 8089

    ###########################
    # Log settings.
    ###########################
    [api.cdn.log]

      # Max service logs size in bytes (default: 15MB)
      serviceMaxSize = 15728640

      # Max step logs size in bytes (default: 15MB)
      stepMaxSize = 15728640

    ######################
    # CDS CDN TCP Configuration
    #######################
    [api.cdn.tcp]

      # Listen address without port, example: 127.0.0.1
      # addr = ""
      port = 8089
```

Looking through the docker-compose.yml - there's no reference to port 8089.  

In the online documentation, I see:  

> CDN
> 
> This component operates CDS CDN to handle storage
> 

I have the impression somehow that this is where log files are shipped to during job execution.  I see logs of the execution steps now.  I don't see CDN as a service that I'm starting.  Is it just part of the core engine?  (i.e. it's part of the API server?)  

The only references I see in the codebase for publicHTTP and publicTCP are in the types.go file.  What are those settings supposed to do?

**Comment by yesnault** [comment]
The cdn service will be available in next release. This service will handle the job log and some documentation will be available at this time. You can ignore the [cdn] section with the release 0.47.0.
