### ISSUE TITLE
api.services settings

### ISSUE THREAD

**Issue by nevetS** [ovh/cds#5526]
I'm confused about this section of the conf.toml file:

Is this for internal health checking?  The settings below are from the docker stack.  I'm thinking healthUrl should point to my own instance?  I'm not finding any documentation about this section.

```
  [[api.services]]
    ID = 0
    PublicKey = ""
    healthPath = "/cds"
    healthPort = "443"
    healthUrl = "https://ovh.github.io"
    name = "sample-service"
    path = "/cds"
    port = "443"
    type = "doc"
    url = "https://ovh.github.io"
```

**Comment by yesnault** [comment]
Yes, it's for doing some checks on an url and display the result in cds status.

**Comment by yesnault** [comment]
this section was removed few release ago.
