### ISSUE TITLE
Local Hatchery on OSX

### ISSUE THREAD

**Issue by nevetS** [ovh/cds#5549]
I haven't tried it yet - I'm mac-less for the time being, but one of the things I wanted to accomplish with CDS was running a local hatchery on OSX for running ios builds of react-native applications.

I just noticed that there is a cds-engine for darwin, a cdsctl for darwin, but I don't see a cds-worker for darwin.  I do see that there are freebsd/openbsd workers, but I'm not entirely sure how it works.  If I run a local hatchery on OSX, is it going to be able to run without a darwin worker binary?

**Comment by yesnault** [comment]
Hi @nevetS , it's in file cds-worker-all.tar.gz in the latest release here: https://github.com/ovh/cds/releases/tag/0.47.0

you can install them with `./cds-engine download workers --config conf.toml`

**Comment by nevetS** [comment]
Thank you.  And I appreciate how responsive this group has been to my questions.  I will be chipping in with at least some help on docs as I get up and running.
