### ISSUE TITLE
github webhook fails on pull request payload

### ISSUE THREAD

**Issue by Pimpre** [ovh/cds#5583]
I wanted to set up the github webhook to run workflows on a commit or on pull request creation.
Everything works fine for `push` events but I have an error on `pull_request` events.
```
runScheduler>dequeueTaskExecutions>doTask>doWebHookExecution>executeRepositoryWebHook>generatePayloadFromGithubRequest: internal server error (caused by: unable ro read github request: {"action": "closed", "number": 2, "pull_request": {...},"repository": {..., "pushed_at": "2020-12-07T15:30:14Z"},"organization": {...},"sender": ...}: json: cannot unmarshal string into Go struct field GithubRepository.repository.pushed_at of type int)
```

According to github documentation, [push event payload](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#push) and [pull_request event payload](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request) are differents.

**Comment by yesnault** [comment]
Hi @Pimpre , you are on release 0.47.0 ?

**Comment by yesnault** [comment]
ok, fixed on https://github.com/ovh/cds/commit/ea9d272a38a535efcb31b5cb632be55ce20fc371, for next release in few weeks.
