### ISSUE TITLE
Please update the sample document

### ISSUE THREAD

**Issue by YLQZ** [ovh/cds#5588]
https://ovh.github.io/cds/hosting/ready-to-run/from-binaries/
./cdsctl signup verify --api-url ... # Get this command from the API Logs
this cmd  unknown how to use  in new vertion 
This leads to can run api and ui  but Can not visit   and auth  
ui cmd sade  wait for api
api cmd sade  auth  faild

**Comment by yesnault** [comment]
In you cds api log, you must have a log containing `cdsctl signup verify --api-url ...`. Run the whole command to signup the user before going ahead.
