### ISSUE TITLE
[GitLab] Triggers moved to GitLab Core in 12.8.

### ISSUE THREAD

**Issue by jchomat** [ovh/cds#5595]
Hello,

It seems that triggers are no longer a gitlab premium feature.

Does it mean that a free gitlab instance can be use for 12.8+ gitlab users ?

The readme shoul be updated in this way if it's true.

BR,
Jérémy

**Comment by yesnault** [comment]
comparison matrix deleted. https://github.com/ovh/cds/pull/6230
