### ISSUE TITLE
cds-cdn failed

### ISSUE THREAD

**Issue by ilya-qpmr** [ovh/cds#5730]
Hi, in your 0.48.0 release, after running the worflow, first pipeline 'Script step' hung with error in cds-cdn "[INFO] pprofLabel>compress>setRequestID>recoverWrap>handle>itemAccessMiddleware>LoadByAPIRefHashAndType>getItem: resource not found action=cdn.(*Service).getItemLogsLinesHandler"
Log from cds-api:
"[ERROR] unable to ping service sample-service: Exec>Serve>Pings>ping>LoadByName>get: resource not found ...
 ... error: unable to load Feature 'cdn-job-logs' from database: ...
 ... error: unable to load Feature 'workflow-retention-maxruns' ...
... error: unable to load Feature 'cdn-artifact' from database:  ...
"
Service status is OK.
cds-cdn configuration:
`{
    "api": {
        "http": {
            "insecure": false,
            "url": "http://cds-api:8081"
        },
        "maxHeartbeatFailures": 10,
        "requestTimeout": 10
    },
    "cache": {
        "lruSize": 134217728,
        "redis": {
            "host": "cds-cache:6379"
        },
        "ttl": 60
    },
    "database": {
        "connectTimeout": 10,
        "host": "cds-db",
        "maxconn": 20,
        "name": "cds",
        "port": 5432,
        "role": "",
        "schema": "cdn",
        "sslmode": "disable",
        "timeout": 3000,
        "user": "cds"
    },
    "http": {
        "addr": "",
        "port": 8089
    },
    "log": {
        "stepLinesRateLimit": 1800,
        "stepMaxSize": 15728640
    },
    "metrics": {
        "frequency": 30
    },
    "name": "cds-cdn",
    "public_http": "http://localhost:8089",
    "public_tcp": "Srv2:8090",
    "storageUnits": {
        "buffers": {
            "local-buffer": {
                "bufferType": "file",
                "local": {
                    "path": "/app/cdn-buffer"
                },
                "redis": null
            },
            "redis": {
                "bufferType": "log",
                "local": null,
                "redis": {
                    "host": "cds-cache:6379"
                }
            }
        },
        "hash_locator_salt": "wu9x6zyi",
        "storages": {
            "cds": {
                "cds": {
                    "host": "http://cds-api:8081",
                    "insecureSkipVerifyTLS": false
                },
                "sync_bandwidth": 128,
                "sync_parallel": 2
            },
            "local": {
                "local": {
                    "path": "/app/cdn-storage"
                },
                "sync_bandwidth": 128,
                "sync_parallel": 2
            }
        },
        "syncNbElements": 100,
        "syncSeconds": 30
    },
    "tcp": {
        "addr": "",
        "globalTCPRateLimit": 2097152,
        "port": 8090
    },
    "url": "http://localhost:8089"
}`

0.47.0 works fine with the default configuration from [here](https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/)
![Screenshot from 2021-03-01 13-06-11](https://user-images.githubusercontent.com/57658520/109483145-ef61ad00-7a8f-11eb-97f2-e8afe9384968.png)

**Comment by richardlt** [comment]
Hi, Is this a fresh CDS install or did you migrate from 0.47 ? I think that the log about loading features is not the problem source (this features are optional and UI catch this).
The error "...LoadByAPIRefHashAndType>getItem: resource not found action..." mean that log data are not in CDN so maybe never received. 
Workers connects to CDN through a TCP socket, the address is the one that is visible in config ("public_tcp": "Srv2:8090"). This address should be resolvable by your workers, can you check if its ok or not ?

**Comment by ilya-qpmr** [comment]
It's a fresh start, I checked the [initial sequence again](https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/). (All containers removed).
My adjustment below:
`export CDS_EDIT_CONFIG="hatchery.local.commonConfiguration.provision.maxWorker=4 hatchery.local.commonConfiguration.provision.maxConcurrentProvisioning=4 vcs.servers.bitbucketcloud.url=https://bitbucket.org vcs.servers.bitbucketcloud.bitbucketcloud.clientId=${CLIENT_ID} vcs.servers.bitbucketcloud.bitbucketcloud.clientSecret=${SECRET}";
docker-compose up cds-edit-config;
docker-compose up -d cds-vcs cds-repositories;
`
that's all.
Socket in LISTEN state
`tcp    LISTEN     0      128                                                  :::8090                                                  :::* `

**Comment by richardlt** [comment]
> I also tried CDS_EDIT_CONFIG="cdn.publicTCP=http://my_public_ip:8090"
The protocol should not be set in publicTCP config can your try with "my_public_ip:8090" ?

**Comment by ilya-qpmr** [comment]
> > I also tried CDS_EDIT_CONFIG="cdn.publicTCP=http://my_public_ip:8090"
> 
> The protocol should not be set in publicTCP config can your try with "my_public_ip:8090" ?

Sorry for this, I also tried 'cdn.publicTCP=my_public_ip:8090', result the same

**Comment by richardlt** [comment]
> Have you tested your initial sequence?) 

As an example, this tutorial is run before publishing our releases to be sure that fresh start is ok: https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/

Another thing you can do to check if the worker is able to join CDN service is to get logs of one worker (using cmd docker ps to get container id then docker logs <container-id>) when it's running. You will be able to see if there are errors on calling CDN service.

**Comment by ilya-qpmr** [comment]
> > Have you tested your initial sequence?)
> 
> As an example, this tutorial is run before publishing our releases to be sure that fresh start is ok: https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/
> 
> Another thing you can do to check if the worker is able to join CDN service is to get logs of one worker (using cmd docker ps to get container id then docker logs ) when it's running. You will be able to see if there are errors on calling CDN service.

You are right, I missed the error message in the hatchery-local log:
`cds-hatchery-local_1  | 2021-03-02 13:19:42 [INFO] hatchery> local> worker> cds-hatchery-local-optimistic-pascal-local-recursing-elion> [gelf] cannot connect to logging server: dial tcp my_public_ip:8090: connect: connection refused caller=github.com/ovh/cds/engine/hatchery/local.localWorkerLogger.Logf source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/engine/hatchery/local/worker_spawn.go source_line=37
`

**Comment by yesnault** [comment]
seems that the cdn service is not started or reachable from hatchery service. telnet my_public_ip 8090 is ok ?

**Comment by ilya-qpmr** [comment]
I tried on the fresh droplet (Ubuntu 20.04.1 LTS) and it work's, but `CDS_EDIT_CONFIG="cdn.publicTCP=my_public_ip:8090"`
**is necessary!**
