### ISSUE TITLE
Worker models error

### ISSUE THREAD

**Issue by ygwane** [ovh/cds#5750]
Hi,

I need help to solve an issue related to worker models.
We use CDS 0.48 release version on fresh install environment. 
Workers are spawned on a swarm hatchery launched on remote server and CDS is launched with docker-compose, the registration of worker model seems to be good but worker model is in error. 

Console output on worker model into CDS UI, display this (no specific error) :
`       p2021-03-01T18:34:18.394199372Z    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       n2021-03-01T18:34:18.394241759Z                                   Dload  Upload   Total   Spent    Left  Speed
        2021-03-01T18:34:18.472359704Z  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.8M  100 19.8M    0     0   254M      0 --:--:-- --:--:-- --:--:--  254M
       S2021-03-01T18:34:18.488106774Z  2021-03-01 18:34:18  [32m[INFO] [0m Registering with Token eyJhbGciOiJS on http://192.168.0.100:8081  [32mcaller [0m github.com/ovh/cds/engine/worker/internal.(*CurrentWorker).Register  [32msource file [0m /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/worker/internal/register.go  [32msource line [0m 15
       )2021-03-01T18:34:18.575704514Z  2021-03-01 18:34:18  [32m[INFO] [0m Unregistering worker  [32mcaller [0m github.com/ovh/cds/engine/worker/internal.(*CurrentWorker).Unregister  [32msource file [0m /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/worker/internal/register.go  [32msource line [0m 66`

Debug log on hatchery and no revelant error in it.
The only warning error that we can see is on CDS API:
`[WARN] service.JWTMiddleware> invalid given jwt token [/auth/consumer/worker/signin]: crypto/rsa: verification error` 

FYI, same environment works perfectly with CDS 0.47 and we try to setup into 2 differents environments.

Thanks in advance for help
Gilles

**Comment by yesnault** [comment]
Hi @ygwane, on the worker model page, what's the value for the flag `need_registration`?

**Comment by ygwane** [comment]
Hi, flag is set to false

**Comment by yesnault** [comment]
ok, so it's not really a problem to use the worker model; This error occurs when the worker try to unregister himself from the api, we will check that. It's not a blocker, this model is fully usable.

**Comment by yesnault** [comment]
@ygwane  on worker model page, above the `Checklist`, do you see a message beginning with `Exec routines killAwolWorker killAndRemove CheckWorkerModelRegister ` ? If yes, can you copy/paste message here?

If you resave the worker model, the worker model should be registered again after few minutes. Do you see the error message agin on unregister?

**Comment by ygwane** [comment]
Yes, here is the message above checklist:
`Exec routines killAwolWorker killAndRemove CheckWorkerModelRegister: internal server error (from: an error occurred when registering the model with container name: /register-youpy-hopeful-but-inspiring-swanson) (caused by: internal server error)`

And yes too, if I resave the worker model, same message appears on worker model UI page and into the api log output
