### ISSUE TITLE
Issue found by Svace static analyzer

### ISSUE THREAD

**Issue by vvdvortsova** [ovh/cds#5840]
Hello
This warning found with the Svace.
Redundant comparison with nil for n.
https://github.com/ovh/cds/blob/f8d2b30d4b400f9ea0ac2612d5d4a2a196447935/sdk/exportentities/v1/workflow.go#L454
Because there is checking for error before.
https://github.com/ovh/cds/blob/f8d2b30d4b400f9ea0ac2612d5d4a2a196447935/sdk/exportentities/v1/workflow.go#L442

**Comment by yesnault** [comment]
no. By reading only processNodeAncestors, it's more clear to check nil on n here, without reading getNode in details.
