### ISSUE TITLE
Jobs waiting after installation

### ISSUE THREAD

**Issue by karfianto** [ovh/cds#5928]
I tried the docker compose installation guide, but all the workers are waiting. 
What's the posssible causes of this?

![image](https://user-images.githubusercontent.com/3934845/132993127-73001eff-beb8-4379-9fae-adddbffb49ef.png)

![image](https://user-images.githubusercontent.com/3934845/132993170-a9c87297-58f9-49e2-bf84-6f8b252527ac.png)

**Comment by yesnault** [comment]
Before starting a worker, CDS have to check if the worker model is ok to be used. The hatchery starts a worker using this worker model, this action is called 'worker registration'. if registration is ok, the worker model can be used.

So, you have two things to check :
 - Do you see a hatchery in your services ? (Admin section -> Monitoring). 
 - In you worker models list : Setting section -> worker models -> the worker model should have the flag 'need registration' to false. If it's true, perhaps you have an error display why on this page.

**Comment by karfianto** [comment]
- Do you see a hatchery in your services ? (Admin section -> Monitoring). : Yes
![image](https://user-images.githubusercontent.com/3934845/133010043-46c258a3-cf68-4fc0-a64a-aeba407cf511.png)

- 'need registration' is already false
![image](https://user-images.githubusercontent.com/3934845/133010265-ca3b6afb-0c01-4103-9860-c8f635950a07.png)

**Comment by karfianto** [comment]
Here's the log of build job
![image](https://user-images.githubusercontent.com/3934845/133010505-f0f0778c-4033-4e17-97b3-d26e339f421f.png)

When I clicked the Script and Display Env Variables here's the output
![image](https://user-images.githubusercontent.com/3934845/133010607-78fcb43c-cc3e-48e6-9c29-0f161dbb0ae8.png)

**Comment by yesnault** [comment]
Can you check the api logs containing the field 'request_id' ?

**Comment by yesnault** [comment]
feel free to reopen if needed.
