### ISSUE TITLE
Non interactive mode for the cdsctl command

### ISSUE THREAD

**Issue by b2p-fred** [ovh/cds#5998]
I tried to 
```
./cdsctl -n environment delete PROJECT env_name
```
but I always have to confirm deletion.

Note that I tried to insert the `-n` between every word of the command ... no matter the position :/ I also tried the same with the `--no-interactive` ... it is also ignored.

**Comment by b2p-fred** [comment]
Bump. Is there any way to force the deletion with the command line interface ?

**Comment by yesnault** [comment]
You can use the `-f` flag:;

```
❯ cdsctl environment delete -h
Delete a CDS environment

Usage:
  cdsctl environment delete [ PROJECT-KEY ] ENVIRONMENT-NAME [flags]

Aliases:
  delete, rm, remove, del

Flags:
      --force   Force delete without confirmation and exit 0 if resource does not exist
