### ISSUE TITLE
Customize rendering of pipelines in a workflow

### ISSUE THREAD

**Issue by Thiht** [ovh/cds#6072]
Hi,
I have a workflow with 15 deployment pipelines at the end (5 applications deployed on 3 environments), and it can be a bit hard to visualize.
Could you add a way to customize the rendering of pipelines? Some customizations ideas: border color, icon, a little colored bullet or tag, etc. Maybe just not background color because if conflicts with the execution status

**Comment by yesnault** [comment]
A new view is under development (with the new ascode engine, under development). We don't do anything on current view until this new system.
