### ISSUE TITLE
Retrieve Logs from Distant Hatchery (OpenStack)

### ISSUE THREAD

**Issue by jqueguiner** [ovh/cds#6180]
### Discussed in https://github.com/ovh/cds/discussions/6179

<div type='discussions-op-text'>

<sup>Originally posted by **jqueguiner** May 20, 2022</sup>
When setting up Open Stack Hatchery logs are not displayed anymore in the UI nor in the CLI stream

I don't have a Graylog setup could it be that?
Is the hatchery sending the logs through the main API ?

thanks</div>

**Comment by yesnault** [comment]
see answer in 6179.
