### ISSUE TITLE
Reset password link doesn’t follow conf.toml

### ISSUE THREAD

**Issue by jqueguiner** [ovh/cds#6229]
when changing domain in conf.toml it doesn’t reflect on the reset password due to this line

https://github.com/ovh/cds/blob/4d4a2d860e5bfa3cd3d349abc4194ef520f8de8e/engine/api/mail/mail.go#L48

**Comment by yesnault** [comment]
Hi @jqueguiner , which attribute did you update?

The attribute used by this url is: `ui` in api `[api.url]` section. You need to restart api after update this value.

**Comment by yesnault** [comment]
I close this issue, feel free to reopen if needed.
