### ISSUE TITLE
Can not login in dashboard afther installing the crd service by docker-compose

### ISSUE THREAD

**Issue by kiragoo** [ovh/cds#6244]
It's my first time using the CDS.
After installing the service about CDS reference to the [docs](https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/).I can't login in as admin (i have already signed up the admin and verified the user:admin).

Details as belows:

* Env:
1. Install the CRD services on a VM:Centos7-x86_64
2. Login as admin on local:Mac-ox.
* The services and status for CDS on vm:
![image](https://user-images.githubusercontent.com/7400711/181454000-8e557c61-6139-4436-84b7-c93901f148fd.png)

* Info about login failed:
1. 
![image](https://user-images.githubusercontent.com/7400711/181445626-92f13b17-2bd8-4555-a8ed-f58f0f01440e.png)
2. logs for cds_cds-api_1:
```
2022-07-28 07:23:23 [INFO] POST | END   | /auth/consumer/local/signin [api.(*API).postAuthLocalSigninHandler] | [200] action=api.(*API).postAuthLocalSigninHandler caller=github.com/ovh/cds/engine/api.(*Router).handle.func1.1 deprecated=false handler=api.(*API).postAuthLocalSigninHandler ip_address=172.18.0.11:38036 latency=149.411631ms latency_num=149411631 method=POST request_id=59e9de2e-3a3b-46a3-bd86-84915de81da5 request_uri=/auth/consumer/local/signin route=/auth/consumer/local/signin source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go source_line=395 status=200 status_num=200 sudo=false
2022-07-28 07:23:23 [INFO] GET | BEGIN | /auth/me [api.(*API).getAuthMe] action=api.(*API).getAuthMe caller=github.com/ovh/cds/engine/api.(*Router).handle.func1 deprecated=false handler=api.(*API).getAuthMe ip_address=172.18.0.11:38036 method=GET request_id=321a074b-6572-48ad-b3a8-a396b175794c request_uri=/auth/me route=/auth/me source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go source_line=374
2022-07-28 07:23:23 [INFO] not authenticated action=api.(*API).getAuthMe caller=github.com/ovh/cds/engine/service.WriteError deprecated=false handler=api.(*API).getAuthMe ip_address=172.18.0.11:38036 method=GET request_id=321a074b-6572-48ad-b3a8-a396b175794c request_uri=/auth/me route=/auth/me source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/engine/service/http.go source_line=155 stack_trace=not authenticated
github.com/ovh/cds/sdk.WithStack
        /tmp/790ad7b9a1a85167593986ed564384b7/run/sdk/error.go:622
github.com/ovh/cds/engine/api.(*API).authMiddleware
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router_middleware_auth.go:82
github.com/ovh/cds/engine/api.(*Router).handle.func1
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go:422
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2084
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go:173
github.com/ovh/cds/engine/api.(*Router).setRequestID.func1
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go:121
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2084
github.com/gorilla/handlers.CompressHandlerLevel.func1
        /go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20160816184729-a5775781a543/compress.go:143
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2084
github.com/ovh/cds/engine/api.(*Router).compress.func1
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go:96
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
        /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/api/router.go:88
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2084
github.com/gorilla/mux.(*Router).ServeHTTP
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2916
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1966
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
```
* Info about user:
1. I have already create the user:admin refer to the [docs](https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/)
`$ ./cdsctl signup --api-url http://localhost:8081 --email admin@localhost.local --username admin --fullname admin
` 
adn verify the user:admin by run the command
`$ VERIFY_CMD=$(docker-compose logs cds-api | grep 'cdsctl signup verify' | cut -d '$' -f2 | xargs) && ./$VERIFY_CMD
`
2. The details for user:admin 
```./cdsctl user me
created      2022-07-28 07:06:50.863413 +0000 UTC
fullname     admin
id           07184e28-416d-4471-bf2c-b8618b5e39df
organization 
ring         ADMIN
username     admin
```

I'll appreciate for your help😀

**Comment by yesnault** [comment]
`cdsctl user me` is ok, you have a 401 because of the session check.
What's the value of your `[api.url]` ? You should have the ip address and not localhost

**Comment by kiragoo** [comment]
@yesnault Tks for your help. 😊

- Configure the [api.url] as 10.100.10.157 ,the ip of vm running the  api service on docker.

- The details of signing up and verifying：
 1.
 ```
[root@host-10-100-10-157 cds]# ./cdsctl signup --api-url http://10.100.10.157:8081 --email admin@localhost.local --username admin --fullname admin
```
  2.
 ```
 ./cdsctl signup verify --api-url http://10.100.10.157:8081 eyJhbGciOiJQUzUxMiIsImtpZCI6IiJ9.eyJ0eXBlIjoidmVyaWZ5TG9jYWxSZWdpc3RyYXRpb25Ub2tlbiIsImV4cGlyZSI6MTY1OTY3ODE0NCwiZGF0YSI6eyJpc19maXJzdF9jb25uZWN0aW9uIjp0cnVlLCJub25jZSI6ImM1ZWFiOGIwLTBhMGMtNGNhMi1iYzA1LWQxNDA1NmI1YTE0NyIsInJlZ2lzdHJhdGlvbl9pZCI6ImYwYWYzYzEwLWFiMTctNGNmMC05NDQ5LWU0NjI1NTdlNTM0MyJ9fQ.1_Iu-NEOI9Gk2fPjJ9-nf8olqotCWWvtti1Pn45dJSDLmNwUp-7AtXZ8g6dr4lp6edIpT5VR-V8kL5texc2T_P7LCRr6DEyNP_NRyhe8M25il6S6VtXBxuL91HXXv4WSY4lXYTfaOpLj_yGVfUq-EdAJOvepmwB2McFyAw4GSRwpmie2LEW4MshkrYyZAhTOgp1D27LOscb61TGKLvAP4MXPw-8CZqoq6kRs6axKi5GGkznqJUWQvmhaWCLa7n0iD_ADvP4Bpa3TBQ8fTNwVpc1KvRVNBaQ2KPU3L5LhMOjRmNC0u0BuiMAs-uBGTDMcAGnBWz5e29zvYwAiT_YCYQ
``` 

The error of  verifying is : `API Error: not authenticated (request_id: cc1b93ef-25f0-4da9-ae99-6dc3339037c7)`

- The details of error:
![image](https://user-images.githubusercontent.com/7400711/182775010-1ef6b44f-5255-4356-9321-1d79a2268627.png)
![image](https://user-images.githubusercontent.com/7400711/182775070-c1d82c10-7ef3-485e-a3bc-a5f824da1ccc.png)

**Comment by ebo-bpi** [comment]
I do have the same issue. followed the docs, but not able to login. I've tried the IP address as well, but that is also not working for me. Logs gives not enough info on the problem.

**Comment by yesnault** [comment]
@ebo-bpi Do you have error only on with your browser ? Is the `cdsctl user me` is ok for you?

**Comment by ebo-bpi** [comment]
Hi, thanks for your reaction! I have followed the docker-compose full example and also tried to run in directly on a remote server.
I have followed this guide to set it up: https://ovh.github.io/cds/hosting/ready-to-run/from-binaries/
I do not use nginx with ssl in front yet. would that make a difference?

**Comment by ebo-bpi** [comment]
@yesnault  cdsctl user me is working. 

error in the browser console:
`error: Object { id: 10, message: "not authenticated", request_id: "b92a0401-b3ab-46c1-a47a-4b6eda737f6c" }
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit()
 }
message: "Http failure response for http://<<HOST>>:8080/cdsapi/auth/me: 401 Unauthorized"
name: "HttpErrorResponse"
ok: false
status: 401
statusText: "Unauthorized"
url: "http://<<HOST>>:8080/cdsapi/auth/me"`

**Comment by yesnault** [comment]
Hi @ebo-bpi , @kiragoo 

I will try to be as clear as possible about this issue.

CDS uses "https only" cookies:
	•	You must use https if you want to access a CDS remotely (not localhost).
	•	On localhost only, you can access with http (not secure)


You want to test CDS in localhost only:
https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/docker-compose/

You want to test CDS from a VM:
https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/full-example/
--> You must configure an SSL (exposed by HAProxy in the doc)

You want to use CDS in production:
It's up to you how you want to maintain your production (k8s, debian package). We do not provide a helm chart for now.
Some information is available at https://ovh.github.io/cds/hosting/ready-to-run/from-binaries/ and you have to expose CDS with a SSL configured and exposed by something as HAproxy.

**Comment by ebo-bpi** [comment]
ok, clear indeed ;) 
https is indeed partly the solution. 
other issue I had was the url for api.url.api. this should be set to https://<public host>/cdsapi and is default set to localhost:8081.

maybe this is something you could add to the documentation, because that is not clear. I found this while looking at the docker-compose guide. 
@kiragoo make sure you use this with ssl and set the api.url api to public host /cdsapi

**Comment by yesnault** [comment]
Default values are ok to develop on CDS. It's not ok for 'production', each prod are quite different. We'll prefer to improve documentation and ensure that important configuration values are well taken into account.

**Comment by ebo-bpi** [comment]
cool thanks! 
Adding some extra documentation on these values in the generated conf file is also fine. quite some stuff is already explained there, but not all of them. 

For the rest I love the product so far! 
Keep up the good work!
