### ISSUE TITLE
Services keeps all logging on INFO although level is set to critical 

### ISSUE THREAD

**Issue by ebo-bpi** [ovh/cds#6290]
I'm running from binaries and have set log level to critical.
after restarting the services still a log of INFO logs are shown.

How do I the log level to only log warnings / errors?

**Comment by ebo-bpi** [comment]
hmm found out that it should be error and not critical.... maybe update the config file documentation?

**Comment by yesnault** [comment]
Hi @ebo-bpi , thank you for this report.
