### ISSUE TITLE
After adding an outgoing webhook you cannot edit it anymore. 

### ISSUE THREAD

**Issue by ebo-bpi** [ovh/cds#6333]
Only way to edit the payload is to edit as code. not a big issue, but would be convenient to edit via UI.

**Comment by yesnault** [comment]
Hi @ebo-bpi , thank you for this report. 

Notice that the outgoing webhook and workflow hook will probably be replaced by a worker command in  a later release (let user to choose to wait or not the end for the workflow triggered).

You can replace the webhook by a simple job, step script, doing curl. It will be the same as the outgoing webhook (with more logs available if you want with curl).

**Comment by ebo-bpi** [comment]
ah ok, I was already thinking of a simple user action to do this... curl is also a simple solution!
