### ISSUE TITLE
"not authenticated" error popup on the main CDS UI SignIn page

### ISSUE THREAD

**Issue by mhatvani** [ovh/cds#6696]
After upgrading from 0.52 to 0.53 when I load the CDS UI page with the Sign in, every time it shows an error popup window with "not authenticated". 

The reason is that in 0.53 the url is automatically extended with a redirect parameter while loading the page. So from
**https://cds-ui-url/**  it will change to **https://cds-ui-url/auth/signin?redirect=%2Fproject%2Flist%2Fall**
![cds_ui_not_authenticated](https://github.com/ovh/cds/assets/149676167/645059d9-78f8-4937-ae44-c898ee448119)

**Comment by yesnault** [comment]
Hi. Sorry for late anwser. It's probably because of the ssl configuration / api.url.ui attribute. You will find ssl configuration examples here: https://ovh.github.io/cds/hosting/ready-to-run/docker-compose/full-example/#configure-ssl

**Comment by mhatvani** [comment]
Hello,

I don't think it's about configuration. If I manually change the url from  https://cds-ui-url/auth/signin?redirect=%2Fproject%2Flist%2Fall   by cutting the redirect part to  https://cds-ui-url/auth/signin the popup won't appear again.

However the redirecting is a new feature in 0.53, previously it was "Home" screen, but now it is hard coded in **ui/src/app/app.routing.ts** file to redirect to project/list/all. And this is what causes the authentication error popup. 

![image](https://github.com/ovh/cds/assets/149676167/9a328f7a-d53d-4ada-a665-4a7f4dae0841)
