### ISSUE TITLE
fix (api): wrong spawn infos language

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#675]
Spawn infos in FR, whole UI is in EN

**Comment by fsamin** [comment]
The bug has been reproduced.
My default language is EN, if I set the language to FR. All the UI switch to FR, but the spawninfos are still in EN. Probably the Accepted-Language header is not override when we set manually the language in the UI

**Comment by yesnault** [comment]
fixed with https://github.com/ovh/cds/pull/3664
