### ISSUE TITLE
fix (cli): consistent list display

### ISSUE THREAD

**Issue by sebgl** [ovh/cds#748]
There are some inconsistencies in the way things are listed in cds-cli:

This is relying on github.com/olekukonko/tablewriter with borders:
```
cds application list MYPROJECT -w
|       NAME        |
|-------------------|
| application1         |
| application2     |
| application3 |
```

This is relying on text/tabwriter (with no borders):
```
cds pipeline list MYPROJECT -w
NAME
pipeline1
pipeline2
pipeline3
```

I would personally prefer the second way (text/tabwriter, no borders) of listing stuff for all commands, since it makes it easier to do bash scripts wrapping cds cli commands.
Example:
```
for pipeline in $(cds pipeline list PROJECT -w | tail -n +2); do
	cds pipeline export PROJECT $pipeline -w > pipelines/$pipeline
done
```

**Comment by yesnault** [comment]
+1, no need tabwriter
