### ISSUE TITLE
Problem with pipeline list parameters and usage in triggers

### ISSUE THREAD

**Issue by mlarose** [ovh/cds#849]
We have several build plans using pipeline parameters of type list to choose between semver release type, specified as patch;minor;major

So that this pipeline can be launched giving the user a choice in items. 

When triggering this pipeline, the user selected value is not sent, instead, the full list of values is sent in the XHR request so that cds.pip.level = patch;minor;major instead of the individual value the user selected.

**Comment by sguiheux** [comment]
It has already Bern fixes #840
