### ISSUE TITLE
feature request: adding a catch mecanism to pipeline jobs

### ISSUE THREAD

**Issue by mlarose** [ovh/cds#873]
# Feature request: adding a catch mecanism to pipeline jobs

## Description

I would like to conditionnally run job steps depending on the result of the previous step. Currently there is only the "final step" options to recover from failed steps. 

I think that implementing such a mecanism favors the reusability of predefined cds action.

## Alternatives

I am suggesting a catch but other options could be considered

- worker commands that:
  * change the status of the current job / stage from failed to passing (effectively implementing the catch in the script, which could be more powerful and flexible than a catch but perhaps less user friendly)
  * return the exit code of the previous task?

- run conditions on steps ?
* run only if previous step is successful|failed|skipped|exitcode == ##?

## Sample use case

I want to conditionnally build an artefact containing dependencies or results that are time consuming to produce (node_modules, ...).

I could use cds cli inside my worker and provide it with credentials and parameters to that effect, but it would be much simpler if I could:

```
<Download CDS Artefact /> 
<script> [catch]
if [ ! -f ./artefact ]; then
    make artefact
fi
</script>
<Upload CDS Artefact />
```

**Comment by blaryjp** [comment]
+1 for this feature, please

**Comment by fsamin** [comment]
What about : 
* pushing the result/exit code of a step in the next step as a cds varriable like `{{.cds.build.step.result}}` and the env variable `CDS_BUILD_STEP_RESULT`?
* add a `ignoreFail` option on all steps ?

This way you can go through your job whatever your step statuses and check by yourself the results if you want.

**Comment by mlarose** [comment]
that would work for me! I suggest {{.cds.build.previousStep.result}} for clarity.

**Comment by yesnault** [comment]
Resume. We:
- On Step: remove existing final attribute.
- On Step: add a new attribute boolean : execute even if the job is failed
- On Step: add a new attribute boolean : don't fail the job is result is not success
- Add {{.cds.build.previousStep.result}} variable

Migration:
Existing final steps: add +100 in exec_order to keep existing behaviour (executed at the end of job)

**Comment by mlarose** [comment]
I do not know how many plans would be broken by removing the final attribute. Maybe deprecate it first?

--> On Step: add a new attribute boolean : execute even if the job is failed 

I am not sure that this one is necessary, given that I can flag the previous/failing step with a "don't fail the job attribute", then I can in the next/catch step check the {{.cds.build.previousStep.result}} and act accordingly, including emitting an exit >0 error to fail the job if I can't recover it.

But then again, what would be the behaviour difference between this and finally? Step ordering?

**Comment by yesnault** [comment]
+100 on internal data exec_order on all existing final steps + "execute even if the job is failed"=true on theses steps prevent us to break something.
This attribute is necessary to keep existing behaviour on all existing plans, so no deprecation, just a new visible attribute on each step (and removing button to add a final step).

**Comment by mlarose** [comment]
👍

**Comment by yesnault** [comment]
doc -> https://ovh.github.io/cds/introduction/introduction.concepts.step/
