### ISSUE TITLE
feature idea : mutex in CDS

### ISSUE THREAD

**Issue by mlarose** [ovh/cds#906]
Priority: low (for now)

Use cases:

when launching plans against a shared resource that do not support concurrent usage, (ex: translator2), it would be nice to limit concurrent accesses.

sample feature set:
- built in command to take/release a project wide mutex
- timeouts
  - to wait for mutex
  - to release mutex automatically if the plan does not do so.
- job fails if mutex can not be taken

miscellaneous: or a semaphore

**Comment by fsamin** [comment]
you talk about"shared resource", do you talk about running your own CDS Worker ?

**Comment by mlarose** [comment]
Hi,

not necessarily. In the case that spawned this need/idea is a job that starts a process on another external system but where that system does not handle concurrency at all. 

I am not going to get into the specific because in this case we can and will modify the system and just get on with it. That's why I indicated "low priority" but just in case you run out of good ideas to improve CDS. ;-p

**Comment by fsamin** [comment]
@mlarose we added a quite simple mutex feature on the new workflows.
I close this issue. Please contact use if you want to discuss about it.
