### ISSUE TITLE
feat (ui): add warning after 5mins of queueing to check warnings if requirements are good

### ISSUE THREAD

**Issue by bnjjj** [ovh/cds#914]

**Comment by yesnault** [comment]
It's already done in "Technical Info"

**Comment by yesnault** [comment]
But, for some use case, as new binary, CDS have to recompute (via worker register) all workers usable on job. We have to add information on SpawnInfos if binary is not in a worker model.

**Comment by yesnault** [comment]
@bnjjj  done with https://github.com/ovh/cds/pull/2252, no?

**Comment by bnjjj** [comment]
yes
